-- GENERATED by assets/blender/export_wall.py - do not hand-edit.
-- Clutter for the 'crenel_hand' wall, in the segment's own space. The builder picks a
-- few of these at random per segment (mercenaries_wall.lua, WallSpawnDecor).

mercenaries.WallDecor = mercenaries.WallDecor or {}
mercenaries.WallDecor["crenel_hand"] = {
    { m = "objects/manmade/common_furniture/barrels/barrel_b.cgf", x = 4.238, y = 0.055, z = 6.002 },
    { m = "objects/manmade/common_furniture/barrels/barrel_b_opened.cgf", x = 1.686, y = 0.076, z = 6.000 },
    { m = "objects/manmade/common_furniture/crates/crate_short.cgf", x = -0.545, y = 0.109, z = 6.000 },
    { m = "objects/manmade/task_specific_props/combat/archery/arrows_disassembled.cgf", x = -1.878, y = -0.624, z = 6.923, rx = 0.00000, ry = -0.00000, rz = 0.59389, s = 0.802 },
    { m = "objects/manmade/task_specific_props/combat/archery/arrows_disassembled.cgf", x = 3.051, y = -0.726, z = 6.923, rx = 0.00000, ry = -0.00000, rz = -0.73472 },
    { m = "objects/manmade/task_specific_props/combat/archery/quiver_with_arrows.cgf", x = -3.689, y = -0.699, z = 6.931, rx = 0.00000, ry = -0.00000, rz = -0.34955 },
    { m = "objects/manmade/task_specific_props/combat/archery/quiver_with_arrows.cgf", x = -2.869, y = -0.096, z = 6.262, rx = 1.42038, ry = -1.16985, rz = -1.40764 },
    { m = "objects/manmade/task_specific_props/combat/archery/quiver_with_arrows.cgf", x = -2.675, y = -0.096, z = 6.262, rx = 1.42038, ry = -1.16985, rz = -1.51588 },
    { m = "objects/manmade/task_specific_props/combat/archery/quiver_with_arrows.cgf", x = 0.548, y = -0.096, z = 6.262, rx = 1.42038, ry = -1.16985, rz = -1.51588 },
    { m = "objects/manmade/task_specific_props/combat/archery/quiver_with_arrows.cgf", x = 2.638, y = -0.096, z = 6.262, rx = 1.42038, ry = -1.16985, rz = -1.51588 },
    { m = "objects/natural/stones/gneiss_stone_a.cgf", x = -1.727, y = -0.158, z = 6.019 },
    { m = "objects/natural/stones/stone_limestone_b.cgf", x = 3.398, y = -0.080, z = 6.073 },
    { m = "objects/natural/stones/stones_group_small.cgf", x = -2.724, y = 0.406, z = 6.000 },
    { m = "objects/natural/stones/stones_group_small.cgf", x = 0.845, y = 0.279, z = 6.000 },
    { m = "objects/natural/stones/stones_group_small.cgf", x = 2.944, y = 0.307, z = 6.000 },
    { m = "objects/natural/stones/stones_group_small.cgf", x = 4.668, y = 0.458, z = 6.000 },
}
