-- Squad formation: which shape the squad marches in, who anchors it, and when it
-- gets rebuilt. The behaviour-tree half is the two ENGINE FORMATION arms plus the
-- formation-owner loop in data/AI/follow.xml. Full write-up: docs/formations.md.
--
-- The engine anchors a formation on whatever entity ran MakeFormation, and the
-- player has no behaviour tree, so one merc is elected to stand in for him: he
-- follows the player, and everyone else FormationFollowers off him. Shapes are
-- authored so nothing ever sits ahead of that leader, which keeps the player at
-- the head of his own squad.
--
-- Shapes live in data/AI/FormationDefinitions.xml, generated by
-- tools/gen_formations.py. That file is a WHOLE-FILE override of the vanilla
-- catalogue - it is not a patchable database table, so there is no merge - and it
-- re-lists all 63 vanilla formations verbatim. Regenerate it after a game update.
--
-- Everything here is deliberately latched. Every earlier version churned:
-- re-electing each tick, re-resolving the preset from a live headcount, or gating
-- on a heartbeat. Each of those rebuilt the formation, and a rebuild makes every
-- follower re-join into a newly assigned spot - which reads as the whole squad
-- milling about. FormationEpoch is the rebuild signal, and nothing bumps it
-- without a reason it can name in the log.

mercenaries.FormationShapeOrder = { "column", "line", "square", "wedge", "circle", "escort" }
mercenaries.FormationShape = "column"

-- Sizes generated per shape. Lua picks the smallest that seats the squad: handing a
-- 50-slot template to six mercs lets the engine drop them in any six of fifty spots
-- and strings them out over the whole template.
-- Steps are deliberately close together - under KeepShape a spot's pose is a rigid
-- rotation about the anchor, so a spot d metres out swings 2*d*sin(theta/2) when the
-- leader turns, and a ladder that jumps 60% in one step jumps that lever arm with it.
mercenaries.FormationSizes = { 6, 10, 14, 18, 24, 30, 40, 50 }
-- Evaluations of a still-growing squad to sit through before the shape is re-dealt.
-- See the note at the grow branch in FormationRebuildCheck.
mercenaries.FormationSettleTicks = 3

-- Master switch for the ENGINE formation system (MakeFormation / FormationFollower). Off, the
-- squad falls through to follow.xml's `~$useFormation` arm - a plain CrimeFollower chain, which
-- is exactly what v1.6 and the bodyguards reference mod use and neither of them has this cost.
--
-- This is the A/B for "is the engine formation the per-merc cost in a crowd": nothing else
-- changes, the men still exist, still render, still fight, still run every other tick. Both
-- halves of the teardown are automatic - the leader's MakeFormation subtree has an EndFormation
-- Cleanup guarded on $useFormation, and every follower's epoch-watch loop fails on ~$useFormation
-- - so flipping this is safe mid-march and reversible. See docs/performance.md.
mercenaries.FormationEnabled  = true

mercenaries.FormationLeader   = nil
mercenaries.FormationEpoch    = 0
mercenaries.FormationName     = nil
mercenaries.FormationCap      = 0
mercenaries.FormationMounted  = nil
mercenaries.SquadSize         = 0
mercenaries.FormationTickMs   = 150

-- How far behind the front-runner the sitting leader must fall before leadership
-- is handed over. Distance ordering churns every step as the squad walks, and each
-- handover rebuilds the formation, so this has to be a real gap and not a tie-break.
-- Mounted needs far more room: the mounted preset is ~64m deep, riders overtake
-- constantly, and at 8m the leader changed every few seconds - the formation was
-- rebuilt so often it never settled, which is what read as "mounted mercs take
-- ages to start following".
mercenaries.FormationLeaderSwapMargin        = 8.0
mercenaries.FormationLeaderSwapMarginMounted = 30.0
-- ...and the challenger must HOLD that lead this long, so one overtake on a corner
-- is not a handover.
mercenaries.FormationLeaderSwapSecs     = 3.0
-- ...and after any swap, no further displacement swap for this long, so a rebuild
-- always gets time to settle.
mercenaries.FormationLeaderSwapCooldown = 6.0
-- THE LEADER MUST STAY NEAR THE FRONT. The distance margin above is a fine tie-break, but
-- at fifty horses the leader was regularly found boxed in mid-pack and stuck there, and a
-- stuck anchor stands the whole squad (2026-09-03). Two rules on top of the margin:
--   rank  - a leader with this many fit men closer to the player than him is replaced
--           after the same hold time, whatever the metre gap - "one of the nearest", as
--           asked, rather than "not too far behind the nearest".
--   stuck - the player has covered FormationLeaderStuckPlayer while the leader covered
--           less than FormationLeaderStuckMove, for FormationLeaderStuckSecs: replaced
--           IMMEDIATELY (no margin, no hold, no cooldown), and the old leader is hauled to
--           just behind the player so he is not left wedged wherever he stopped.
-- Rank is OFF (0). Riders overtake each other constantly, so at fifty horses any rank rule
-- is a swap generator, and every swap is a rebuild every rider has to re-join. "The leader
-- should not be constantly changed" (2026-09-03).
mercenaries.FormationLeaderMaxRank      = 0
-- Stuck, second version. The first (3 s, 1.5 m vs 6 m, immediate swap) fired on every
-- freshly elected mounted leader before he had so much as started - mount, WaitAction,
-- riders re-acquiring - and handed the job to the next man, who was then in the same
-- state: five "leader stuck" rebuilds in a row (2026-09-03). So:
--   * a grace after ANY rebuild or swap, during which nobody is stuck;
--   * a long window, longer still mounted, and the player must be well away as well as
--     moving - riding a circle beside a parked leader is not him being stuck;
--   * the FIRST response is a haul only, no swap and no rebuild. Only a second stuck
--     inside the swap window hands the job over, and never more than once a cooldown.
mercenaries.FormationLeaderStuckGraceSecs   = 15.0
mercenaries.FormationLeaderStuckSecs        = 8.0
mercenaries.FormationLeaderStuckSecsMounted = 12.0
mercenaries.FormationLeaderStuckMove        = 2.0
mercenaries.FormationLeaderStuckPlayer      = 15.0
mercenaries.FormationLeaderStuckFar         = 20.0
mercenaries.FormationLeaderStuckSwapWindow  = 40.0
mercenaries.FormationLeaderStuckCooldown    = 20.0

-- KeepShape on foot: it is the only mode that holds an authored shape. Relaxed
-- drifts and MoveHistory replays the leader's path, so both blur the geometry.
-- Mounted overrides this to MoveHistory in follow.xml - no vanilla mounted
-- formation uses KeepShape, and rigid geometry is not something a horse can hold.
mercenaries.FormationModeCode = 1
mercenaries.FormationRelocate = false
-- Shape-specific mode defaults, applied while no mode is pinned. See UpdateFormationRole.
mercenaries.FormationShapeMode = { line = 0 }   -- 0 Relaxed
mercenaries.FormationModeNames = { [0] = "Relaxed", [1] = "KeepShape", [2] = "MoveHistory" }
mercenaries.FormationModeLocKeys = { [0] = "merc_form_mode_relaxed", [1] = "merc_form_mode_keepshape", [2] = "merc_form_mode_movehistory" }

-- Formation shape chosen from dialogue. Count-encoded on one token the way the
-- archer stance is: the quest grants Amount = N and N indexes FormationShapeOrder,
-- so six shapes need one item class instead of six. Fed by both the E-dialog and
-- the silent order wheel.
mercenaries.TokenIDFormation = "679a655e-189d-4519-b437-ccc4b92be51d"

-- Build a preset name guaranteed to exist in FormationDefinitions.xml. NEVER
-- hardcode one: the size ladder has changed several times, and a name carrying a
-- size that is no longer generated resolves to nothing, MakeFormation returns a
-- null handle, and the squad silently drops to the follow chain - which looks like
-- a column and is indistinguishable from the formation system being broken.
function mercenaries:FormationPresetName(size)
    if self.FormationShape == "vanilla" then
        return ((size or 0) <= 8) and "followNPC" or "infantryMen20"
    end
    -- Diagnostic shape only (merc_formation_control). A name that exists in NO
    -- catalogue, ours or the game's. It answers the one question the OK/NULL log
    -- line cannot answer on its own: if MakeFormation reports OK even for this,
    -- then the engine hands back a handle for any name at all and a null handle is
    -- not a usable signal. See docs/formations.md.
    if self.FormationShape == "control" then
        return "merc_control_no_such_formation"
    end
    local pick = self.FormationSizes[#self.FormationSizes]
    for _, n in ipairs(self.FormationSizes) do
        if (size or 0) <= n then pick = n break end
    end
    -- Mounted has exactly one shape: a triple column at horse spacing. The infantry
    -- shapes assume a 2m footprint and a body that can turn on the spot; a horse
    -- needs 3.5m files, 4m ranks, and corners wide.
    local shape = _G.PlayerMounted and "mounted" or self.FormationShape
    return "merc_" .. shape .. tostring(pick)
end

-- Put a stuck (ex-)leader just behind the player. The same recipe the stall ladder's haul
-- uses. A MOUNTED man is dismounted first: SetPos does not bring the horse, and a rider
-- moved without it is stranded beside a horse that is somewhere else (mercenaries_teleport.lua).
-- The horse lifecycle re-mounts him on the spot - instantly, now that it ForceMounts.
function mercenaries:LeaderUnstick(ent)
    if not ent then return end
    local moved = false
    pcall(function()
        if ent.human and ent.human.IsMounted and ent.human:IsMounted() then
            pcall(function() ent.human:ForceDismount() end)
        end
        local base = self:GetSafeSpawnPosition(player, 8)
        if not base then return end
        local tp = self:FindValidGround({
            x = base.x + (math.random() - 0.5) * 3.0,
            y = base.y + (math.random() - 0.5) * 3.0,
            z = base.z,
        }, base.z)
        tp = self:TeleportKeepBehindLeader(tp) or tp
        ent:SetPos(tp)
        pcall(function() self:NoteTeleport(ent) end)
        moved = true
    end)
    System.LogAlways("[MercForm] stuck leader " .. tostring(ent and ent.GetName and ent:GetName()) ..
                     (moved and " hauled to just behind the player" or " - found nowhere to haul him to"))
end

-- Once per FormationTickMs. Picks the leader and the preset, and bumps the epoch
-- only when something real changed.
function mercenaries:UpdateFormationLeader()
    local pp
    pcall(function() pp = player and player:GetWorldPos() end)

    local best, bestD, count = nil, nil, 0
    local leaderStillOk, leaderD = false, nil
    local leaderHurt = false
    -- Fallback tiers, in order of preference: a hurt man anchors the squad only when
    -- every fit man is gone, and a man still finishing a camp activity only when even
    -- the hurt ones are. Camp-busy ranks LAST because he physically cannot walk yet -
    -- an anchor that cannot walk stands the entire squad.
    local hurtBest, hurtBestD = nil, nil
    local busyBest, busyBestD = nil, nil
    -- Constant across every iteration; rebuilding it per-merc was pure waste.
    local leaderStr = self.FormationLeader and tostring(self.FormationLeader) or nil
    -- Distances of every FIT man, for the rank rule (FormationLeaderMaxRank).
    local fitDists = {}
    local leaderEnt = nil

    for _, ent in pairs(self.ActiveMercs) do
        local wuid = ent and (ent.this and ent.this.id or ent.id)
        if self:IsFormationEligible(ent, wuid) then
            count = count + 1

            -- NEAREST to the player leads. The formation hangs off the leader, so
            -- if he is buried inside the pack the whole shape is anchored in the
            -- middle of a crowd he cannot walk out of - at 50 mercs that turns the
            -- squad into a shapeless mass that stops tracking the player at all.
            -- Whoever is closest to the player is by definition on the outside of
            -- the mass, facing the way it needs to go.
            local d = 0
            if pp then
                -- PerfPos is refreshed every 50ms; nil just means not scanned yet.
                local mp = self:PerfMercPos(wuid) or ent:GetWorldPos()
                if mp then
                    local dx, dy = pp.x - mp.x, pp.y - mp.y
                    d = math.sqrt(dx * dx + dy * dy)
                end
            end

            -- A man who was mid camp-activity when camp came down is skipped: his tree is
            -- still playing the drill/eat animation and cannot walk, and an anchor that
            -- cannot walk stands the whole squad. In practice that leaves the camp guards,
            -- who were already patrolling. See CampBusyUntil in mercenaries_camp.lua.
            local busy = self.IsCampBusy and self:IsCampBusy(wuid) or false
            -- ...and a man under the injured floor does not lead either. The anchor is the
            -- one merc the whole formation hangs off and the one who walks nearest the
            -- player, so he is both the most visible man in the squad and the one whose
            -- death costs the most - he re-elects, which rebuilds the formation and makes
            -- every follower re-join. Same threshold as the HUD's injured buff and the
            -- camp bed-rest bias, so "injured" means one thing across the mod.
            -- Read straight off the entity we already hold. LogiIsInjured answers the same
            -- question but scans ActiveMercs for the key, which at 150ms over fifty men is
            -- O(squad^2) a tick. Same constant, so the two cannot disagree.
            local hurt = false
            pcall(function()
                local hp = tonumber(ent.soul:GetState('health'))
                hurt = (hp ~= nil) and (hp < (self.InjuredHealthPct or 50))
            end)

            if leaderStr and tostring(wuid) == leaderStr then leaderEnt = ent end
            if not busy and not hurt then
                if leaderStr and tostring(wuid) == leaderStr then
                    leaderStillOk, leaderD = true, d
                end
                fitDists[#fitDists + 1] = d
                if not bestD or d < bestD then best, bestD = wuid, d end
            elseif not busy then
                -- Still a usable anchor, just not a preferred one: he keeps the job while
                -- he holds it rather than being torn out the instant he is scratched.
                if leaderStr and tostring(wuid) == leaderStr then
                    leaderStillOk, leaderD, leaderHurt = true, d, true
                end
                if not hurtBestD or d < hurtBestD then hurtBest, hurtBestD = wuid, d end
            else
                -- A busy INCUMBENT keeps the job too. Without this he never registers as
                -- still eligible, so the immediate-replace branch below re-elects the
                -- nearest busy man on every tick - and each swap bumps the epoch, which
                -- rebuilds the formation and makes every follower re-acquire a slot. That
                -- is a squad that never settles, which is what a camp deploy produced
                -- while the whole out-party was (wrongly) marked busy. leaderHurt is the
                -- same demotion signal: hand over as soon as a fit man exists.
                if leaderStr and tostring(wuid) == leaderStr then
                    leaderStillOk, leaderD, leaderHurt = true, d, true
                end
                if not busyBestD or d < busyBestD then busyBest, busyBestD = wuid, d end
            end
        end
    end

    -- Held before the fallbacks below overwrite it: "is there a FIT man to hand the
    -- job to" is a different question from "who anchors the squad", and the injured
    -- demotion needs the first one.
    local fitBest = best

    -- Nobody fit: better a hurt anchor than none, and a winding-down one than that.
    if not best then best, bestD = hurtBest, hurtBestD end
    if not best then best, bestD = busyBest, busyBestD end

    self.SquadSize = count

    local reason = nil

    -- Hysteresis, in THREE parts. Every leader change runs EndFormation +
    -- MakeFormation and forces every follower to re-acquire a slot, so a swap is
    -- expensive and must be rare. Distance alone was not enough: this runs every
    -- 150ms, and mounted riders overtake each other constantly, which produced
    -- "leader displaced" rebuilds in a steady stream - the squad never settled
    -- long enough to form up, which is what "mounted mercs take ages to follow"
    -- actually was.
    --   1. margin   - the challenger must be clearly ahead, and MUCH clearer when
    --                 mounted, because the mounted preset is ~64m deep and being
    --                 20m ahead of the leader is normal, not exceptional.
    --   2. duration - he must hold that lead continuously, so a momentary overtake
    --                 while cornering is ignored.
    --   3. cooldown - no second swap straight after one, so a rebuild always gets
    --                 time to actually settle before another can start.
    -- A leader who is dead or no longer eligible is replaced IMMEDIATELY: that is
    -- not churn, and none of the three apply to it.
    local now = 0
    pcall(function() now = System.GetCurrTime() or 0 end)

    local mounted = _G.PlayerMounted and true or false
    local margin  = mounted and self.FormationLeaderSwapMarginMounted
                            or  self.FormationLeaderSwapMargin

    -- Rank: how many fit men stand closer to the player than the leader does. Off at 0.
    local outranked = false
    local maxRank = self.FormationLeaderMaxRank or 0
    if maxRank > 0 and leaderStillOk and leaderD then
        local closer = 0
        for _, d in ipairs(fitDists) do if d < leaderD then closer = closer + 1 end end
        outranked = closer >= maxRank
    end

    -- Stuck: the leader's own ground covered against the player's, over a window that
    -- starts only after the grace. Anchors re-set whenever he moves, the leader changes,
    -- or the epoch does (a rebuild is a fresh start for him too).
    local stuck, stuckWhy = false, nil
    if leaderStillOk and leaderEnt and pp then
        local lp
        pcall(function() lp = leaderEnt:GetWorldPos() end)
        local a = self._leadStuckAnchor
        if lp then
            if not a or a.who ~= leaderStr or a.epoch ~= self.FormationEpoch then
                self._leadStuckAnchor = { who = leaderStr, epoch = self.FormationEpoch,
                                          x = lp.x, y = lp.y, px = pp.x, py = pp.y, at = now,
                                          graceUntil = now + (self.FormationLeaderStuckGraceSecs or 15.0) }
            elseif now < (a.graceUntil or 0) then
                -- Freshly elected or freshly rebuilt: he is allowed to be standing still.
                a.x, a.y, a.px, a.py, a.at = lp.x, lp.y, pp.x, pp.y, now
            else
                local lm = math.sqrt((lp.x - a.x) ^ 2 + (lp.y - a.y) ^ 2)
                local pm = math.sqrt((pp.x - a.px) ^ 2 + (pp.y - a.py) ^ 2)
                local need = mounted and (self.FormationLeaderStuckSecsMounted or 12.0)
                                      or (self.FormationLeaderStuckSecs or 8.0)
                if lm >= (self.FormationLeaderStuckMove or 2.0) then
                    a.x, a.y, a.px, a.py, a.at = lp.x, lp.y, pp.x, pp.y, now
                elseif pm >= (self.FormationLeaderStuckPlayer or 15.0)
                       and leaderD >= (self.FormationLeaderStuckFar or 20.0)
                       and (now - a.at) >= need then
                    stuck = true
                    stuckWhy = string.format("leader moved %.1fm while the player moved %.0fm over %.0fs, %.0fm apart%s",
                                             lm, pm, now - a.at, leaderD, mounted and ", mounted" or "")
                end
            end
        end
    else
        self._leadStuckAnchor = nil
    end
    -- One stuck action per cooldown, whatever kind.
    if stuck and self._leadStuckActAt and (now - self._leadStuckActAt) < (self.FormationLeaderStuckCooldown or 20.0) then
        stuck = false
    end

    local ahead = leaderStillOk and bestD and leaderD
                  and ((leaderD - bestD) > margin or outranked)
                  and tostring(best or '') ~= tostring(self.FormationLeader or '')

    if ahead then
        -- Restart the clock whenever the challenger changes, so the timer only ever
        -- measures ONE man holding the lead.
        if tostring(self._leadChallenger or '') ~= tostring(best or '') then
            self._leadChallenger  = best
            self._leadChallengeAt = now
        end
    else
        self._leadChallenger, self._leadChallengeAt = nil, nil
    end

    local held    = ahead and self._leadChallengeAt
                    and (now - self._leadChallengeAt) >= self.FormationLeaderSwapSecs
    local cooling = self._leadSwapAt
                    and (now - self._leadSwapAt) < self.FormationLeaderSwapCooldown

    if not leaderStillOk then
        if tostring(best or '') ~= tostring(self.FormationLeader or '') then reason = "leader" end
        self.FormationLeader = best
        self._leadSwapAt = now
        self._leadChallenger, self._leadChallengeAt = nil, nil
    elseif stuck then
        -- An anchor that is not moving while the player is. The least that fixes it is a
        -- haul: put him behind the player and let him carry on leading - no swap, no
        -- rebuild, nobody re-joins anything. Only if he is stuck AGAIN inside the swap
        -- window is the job handed over, because then the haul did not cure him.
        self._leadStuckActAt = now
        local again = self._leadStuckHauledAt and (now - self._leadStuckHauledAt) < (self.FormationLeaderStuckSwapWindow or 40.0)
        if again and fitBest and tostring(fitBest) ~= tostring(self.FormationLeader or '') then
            reason = "leader stuck"
            System.LogAlways("[MercForm] leader stuck twice inside " .. tostring(self.FormationLeaderStuckSwapWindow or 40) ..
                             "s - handing the job over (" .. tostring(stuckWhy) .. ")")
            local old = leaderEnt
            self.FormationLeader = fitBest
            self._leadSwapAt = now
            self._leadChallenger, self._leadChallengeAt = nil, nil
            self._leadStuckAnchor, self._leadStuckHauledAt = nil, nil
            pcall(function() self:LeaderUnstick(old) end)
        else
            System.LogAlways("[MercForm] leader stuck - hauling him, keeping him as leader (" .. tostring(stuckWhy) .. ")")
            self._leadStuckHauledAt = now
            self._leadStuckAnchor = nil
            pcall(function() self:LeaderUnstick(leaderEnt) end)
        end
    elseif leaderHurt and fitBest and tostring(fitBest) ~= tostring(self.FormationLeader or '')
           and not cooling then
        -- Hand the job to a fit man. Bounded by the SAME cooldown as a displacement
        -- swap and for the same reason: health only falls during a fight, so without it
        -- a hard scrap would demote leader after leader as each one crosses the floor,
        -- and every demotion rebuilds the formation and makes fifty men re-join. Once
        -- every FormationLeaderSwapCooldown at worst. Deliberately NOT the immediate
        -- path above - that one is for a leader who is dead or gone, which is not a
        -- preference but an emergency.
        reason = "leader injured"
        self.FormationLeader = fitBest
        self._leadSwapAt = now
        self._leadChallenger, self._leadChallengeAt = nil, nil
    elseif held and not cooling then
        reason = "leader displaced"
        self.FormationLeader = best
        self._leadSwapAt = now
        self._leadChallenger, self._leadChallengeAt = nil, nil
    end

    local followers = math.max(count - 1, 0)
    local cap = self.FormationCap or 0

    -- Mounting swaps the whole shape (infantry spacing -> horse spacing), so it has
    -- to defeat the grow-only latch below. This is a real state change, not the
    -- eligibility noise the latch exists to absorb.
    local mounted = _G.PlayerMounted and true or false
    if mounted ~= self.FormationMounted then
        self.FormationMounted = mounted
        self.FormationName = nil
        self.FormationCap = 0
        cap = 0
        reason = reason or (mounted and "mounted" or "dismounted")
    end

    -- Grows immediately; shrinks only once the squad is clearly inside the next size
    -- down, so hovering on a boundary cannot oscillate. Without any shrink at all, a
    -- squad that peaks at 24 and then loses 8 keeps the 24-spot template and
    -- scatters the survivors across it.
    -- A GROWING squad settles before the shape is re-dealt. Hiring fifty men one at a time
    -- crosses six size boundaries (6, 10, 14, 18, 24, 30, 40, 50) and each crossing rebuilt
    -- the formation, and every rebuild makes every follower re-acquire a slot. For an
    -- ARCHER that is fatal rather than untidy: FormationFollower is his only locomotion
    -- (see archer_scheduler.xml), so a man dropped out of it mid-rebuild simply stands
    -- where he is. Measured 2026-09-03, one mass hire: 104 archer stalls against 2 for
    -- foot, "a lot just stood around, the formation never assembled". So a grow waits for
    -- the count to stop moving - unless there is no formation at all, which must not wait.
    local settling = false
    if self.FormationName and followers > cap then
        if followers ~= (self._formLastFollowers or -1) then
            self._formLastFollowers = followers
            self._formSettleTicks = 0
            settling = true
        else
            self._formSettleTicks = (self._formSettleTicks or 0) + 1
            settling = (self._formSettleTicks < (self.FormationSettleTicks or 3))
        end
        if settling and not self._formSettleNoted then
            self._formSettleNoted = true
            System.LogAlways(string.format(
                "[MercForm] the squad is still growing (%d followers, shape seats %d) - holding the rebuild until it settles",
                followers, cap))
        end
    else
        self._formLastFollowers, self._formSettleTicks, self._formSettleNoted = followers, 0, false
    end

    local want = nil
    if settling then
        want = nil
    elseif followers > cap or not self.FormationName then
        self._formSettleNoted = false
        want = self.FormationSizes[#self.FormationSizes]
        for _, n in ipairs(self.FormationSizes) do
            if followers <= n then want = n break end
        end
    else
        local smaller = nil
        for _, n in ipairs(self.FormationSizes) do
            if n < cap then smaller = n end
        end
        if smaller and followers <= (smaller - 2) then want = smaller end
    end

    if want then
        local name = self:FormationPresetName(want)
        if name ~= self.FormationName then
            reason = reason or ((want > cap) and "grow" or "shrink")
            self.FormationName = name
            self.FormationCap  = want
        end
    end

    if reason then
        self.FormationEpoch = (self.FormationEpoch or 0) + 1
        System.LogAlways(string.format('[MercForm] rebuild #%d (%s) preset=%s leader=%s',
            self.FormationEpoch, reason, tostring(self.FormationName), tostring(self.FormationLeader)))
    end
end

-- NO AUTOMATIC FORMATION-MODE SWITCHING. This was tried as "sprint relief" - KeepShape while
-- walking, MoveHistory while the player sprints - and it is a trap in a DEEP formation.
--
-- merc_column50 is 45m from front spot to back spot. KeepShape places that back spot as a
-- rigid offset behind the leader's facing; MoveHistory places it 45m back along the path he
-- actually walked. After any turn those are two completely different points, tens of metres
-- apart, so every mode switch teleported each follower's TARGET and the man ran off to it -
-- the "everyone except the leader runs 20m away and then comes back" bug. It fired exactly
-- when the player's speed crossed the threshold, i.e. whenever he got a little ahead.
--
-- The keep-up problem it was meant to solve is handled properly by the merc_keepup_buff
-- (rms*1.3): make the followers faster, do not move the goalposts. Leave the mode alone.

-- ---------------------------------------------------------------------------
-- Follow spread diagnostic: merc_follow_stats 1
--
-- Answers "are they keeping up, and who is not" with numbers rather than impressions.
-- Logs the player's measured speed, whether the formation is loosened, and the SPREAD of
-- the squad's distance to the player (nearest / median / worst) plus how many are past the
-- teleport line. A healthy column has a stable median and a worst that does not climb.
-- ---------------------------------------------------------------------------
mercenaries.FollowStats = false
mercenaries.FollowStatsEvery = 2.0

function mercenaries:FollowStatsSet(v)
    self.FollowStats = (tostring(v or ''):match('1') ~= nil)
    System.LogAlways('[MercSpread] logging ' .. (self.FollowStats and 'ON' or 'OFF'))
end

function mercenaries:FollowStatsTick()
    if not self.FollowStats then return end
    local now = 0
    pcall(function() now = System.GetCurrTime() or 0 end)
    if self._fsAt and (now - self._fsAt) < self.FollowStatsEvery then return end
    self._fsAt = now

    pcall(function()
        local pp = player and player:GetWorldPos()
        if not pp then return end
        local gate = (self.TeleportDistance and self:TeleportDistance()) or 50.0
        local d, far = {}, 0
        -- inSlot/followers is the headline number: "8 men following" with 0 in a slot
        -- is the blob, and it is indistinguishable from a healthy squad by eye.
        local leader = self.FormationLeader and tostring(self.FormationLeader) or nil
        local inSlot, followers = 0, 0
        for _, ent in pairs(self.ActiveMercs or {}) do
            local mp = ent:GetWorldPos()
            if mp then
                local dx, dy = pp.x - mp.x, pp.y - mp.y
                local v = math.sqrt(dx * dx + dy * dy)
                table.insert(d, v)
                if v > gate then far = far + 1 end
            end
            local w = ent and (ent.this and ent.this.id or ent.id)
            if w and tostring(w) ~= leader then
                followers = followers + 1
                if (self.FormationInSlot or {})[tostring(w)] then inSlot = inSlot + 1 end
            end
        end
        if #d == 0 then return end
        table.sort(d)

        -- Epoch, mode and leader are logged because they are the three things that can move a
        -- follower's TARGET rather than the follower: a formation rebuild, a mode change, or a
        -- new anchor. If the spread jumps on the same tick one of these changes, the squad is
        -- chasing a moved goalpost, not failing to keep up.
        System.LogAlways(string.format(
            '[MercSpread] pSpeed=%.1f n=%d near=%.1f med=%.1f worst=%.1f beyondGate=%d | inFormation=%d/%d epoch=%d mode=%d preset=%s',
            self.PlayerSpeed or 0, #d,
            d[1], d[math.ceil(#d / 2)], d[#d], far,
            inSlot, followers,
            self.FormationEpoch or 0, self.FormationModeCode or 1,
            tostring(self.FormationName)))
    end)
end

mercenaries:DevCommand("merc_follow_stats", "mercenaries:FollowStatsSet('%line')",
                   "Log squad spread and player speed: merc_follow_stats 1 | 0")

-- Slot body: work only. The scheduler gates on ActiveMercs/player before calling
-- this; FormationLoop below is the legacy self-arming path used when merc_sched is
-- off, so it keeps its own gate. See docs/performance.md.
function mercenaries:FormationLoopBody()
    local ok, err = pcall(function()
        if next(mercenaries.ActiveMercs) and player then
            mercenaries:UpdateFormationLeader()
            mercenaries:UpdateFormationFront()
            mercenaries:FollowStatsTick()
        end
    end)
    if not ok then System.LogAlways('[MercForm] FormationLoop Error: ' .. tostring(err)) end
end

function mercenaries.FormationLoop()
    mercenaries:FormationLoopBody()
    if not mercenaries.SchedRunning then
        Script.SetTimerForFunction(mercenaries.FormationTickMs, "mercenaries.FormationLoop")
    end
end

-- ---------------------------------------------------------------------------
-- NAMED COMPANIONS RIDE AT THE FRONT.
--
-- FormationFollower takes a PreferredPositions string naming a <Spot> in the preset,
-- and our generated shapes name their spots by rank (see tools/gen_formations.py).
-- Without it the engine drops each follower in any free spot, so the one man the
-- player actually hired for himself was as likely to be at the back of forty as at
-- the front. Heroes ask for the front-most band; everyone else asks for nothing and
-- fills in around them.
--
-- The spot NAMES differ per shape, so this is derived from the live preset rather
-- than hardcoded - a name that does not exist in the current formation is at best a
-- silent fallback and at worst a failed node (see docs/formations.md).
mercenaries.FormationFrontSpotName = {
    column = "front", line = "front", square = "front", wedge = "front",
    circle = "inner",
    -- Escort is two files flanking the subject; it has no front to be at.
    escort = nil,
}
mercenaries.FormationFrontSpotMounted = "rank1"

-- How many men may ask for that band, per shape. This is the MINIMUM count of
-- front-named spots across the whole size ladder, so the request can never exceed
-- what the smallest preset of that shape actually has - ask for a full band and the
-- overflow men fail the node, drop to the time-boxed CrimeFollower fallback, and
-- retry every 1.5s for ever, which is visible churn. Regenerate alongside
-- tools/gen_formations.py if the shapes change.
mercenaries.FormationFrontSpots = {
    column = 3, line = 6, square = 5, wedge = 4, circle = 6, escort = 0,
}
mercenaries.FormationFrontSpotsMounted = 2

function mercenaries:FormationFrontSpot()
    if _G.PlayerMounted then
        return self.FormationFrontSpotMounted, self.FormationFrontSpotsMounted
    end
    local shape = self.FormationShape
    -- The stock vanilla presets are somebody else's catalogue; their spot names are
    -- not ours to guess.
    local name = shape and self.FormationFrontSpotName[shape] or nil
    if not name then return nil, 0 end
    return name, (self.FormationFrontSpots[shape] or 0)
end

-- Which heroes get the front band, recomputed with the leader tick. Sorted by name so
-- the same men keep the same standing: re-ranking them each pass would re-issue a
-- different PreferredPositions every tick and make them swap places on the march.
mercenaries.FormationFrontOf = {}      -- [wuidStr] = spot name

function mercenaries:UpdateFormationFront()
    -- Once a second, not every leader tick: IsHero costs a GetName per merc and nothing
    -- here changes fast. Recomputed at once on a rebuild, because the epoch is what
    -- carries a shape change - and the spot NAMES are shape-specific.
    local now = 0
    pcall(function() now = System.GetCurrTime() or 0 end)
    local leaderKey = self.FormationLeader and tostring(self.FormationLeader) or nil
    if self._ffAt and (now - self._ffAt) < 1.0
       and self._ffEpoch == self.FormationEpoch
       and self._ffLeader == leaderKey then
        return
    end
    self._ffAt, self._ffEpoch, self._ffLeader = now, self.FormationEpoch, leaderKey

    local spot, slots = self:FormationFrontSpot()
    local out = {}
    if spot and slots > 0 then
        local heroes = {}
        for _, ent in pairs(self.ActiveMercs or {}) do
            local wuid = ent and (ent.this and ent.this.id or ent.id)
            if wuid and self:IsHero(ent) and self:IsFormationEligible(ent, wuid) then
                local n
                pcall(function() n = ent:GetName() end)
                table.insert(heroes, { key = tostring(wuid), name = tostring(n or wuid) })
            end
        end
        table.sort(heroes, function(a, b) return a.name < b.name end)
        -- The leader is already the front-most man in the shape and holds no spot of
        -- his own, so he never consumes one of these.
        local n = 0
        for _, h in ipairs(heroes) do
            if h.key ~= leaderKey then
                if n >= slots then break end
                out[h.key] = spot
                n = n + 1
            end
        end
    end
    self.FormationFrontOf = out
end

-- [wuidStr] = true while that merc is actually inside FormationFollower, written
-- from the flag follow.xml's locomotion arms set. This is the only honest answer to
-- "is the squad in formation": useFormation says we ASKED for one, this says he got
-- a slot. merc_follow_stats prints both.
mercenaries.FormationInSlot = {}
mercenaries.FormationSlotAt  = {}    -- [wuidStr] = when he last published the line above

-- Per merc, from follow.xml's updater loop.
function mercenaries:UpdateFormationRole(bt_data, myWuid)
    local ok, err = pcall(function()
        local slotKey = tostring(myWuid)
        self.FormationInSlot[slotKey] = (bt_data.inFormation == true)
        -- ...and WHEN he said so. This runs from follow.xml, so a fresh stamp is proof his
        -- tree is alive; a man whose tree died stops stamping and his claim goes stale. That
        -- is what makes the flag safe to trust in DismountVerify - see FormationSlotFresh.
        local slotNow = 0
        pcall(function() slotNow = System.GetCurrTime() or 0 end)
        self.FormationSlotAt[slotKey] = slotNow

        bt_data.useFormation      = false
        bt_data.isFormationLeader = false
        -- Reset with the rest, or a man who drops out of the formation carries his last
        -- preference into whatever shape he re-joins - and the spot names are per-shape.
        bt_data.preferredSpot     = ""
        bt_data.formationEpoch    = self.FormationEpoch or 0
        -- Per-shape default, unless the player pinned a mode by hand. A LINE is wide and
        -- shallow: under KeepShape the men at its ends have to sweep an arc of half-width
        -- times the turn angle every time the player turns, and at fifty they cannot -
        -- "they get lost at the back" (2026-09-03). Relaxed is the engine's loose mode
        -- (vanilla's formationData default), so the ends lag the turn instead of chasing
        -- a rigidly rotated spot. merc_form_keepshape pins it back.
        local modeCode = self.FormationModeCode or 1
        if not self.FormationModePinned then
            local sm = (self.FormationShapeMode or {})[self.FormationShape]
            if sm ~= nil then modeCode = sm end
        end
        bt_data.formationModeCode = modeCode
        bt_data.formationRelocate = self.FormationRelocate or false
        -- Derived, never hardcoded, so it always names a preset that exists for the
        -- current shape and ladder.
        bt_data.formationName     = self.FormationName
                                    or self:FormationPresetName(math.max((self.SquadSize or 1) - 1, 0))

        -- The SQUAD-WIDE reasons to stand the formation down. By eye they are all the
        -- same thing - men trailing the player in a clump - so `off` names which one
        -- it was and logs once per change: that is how "the formation is broken" gets
        -- told apart from "a hold order is still standing" without guessing.
        -- Per-merc ineligibility below is deliberately NOT logged here; it differs
        -- from man to man and would flip the shared reason every pass.
        local off = nil
        -- A hold or escort order routes every man individually through nav_goto; an
        -- engine formation running alongside it would be a second set of destinations
        -- pulling the same NPCs somewhere else.
        if not self.FormationEnabled then off = "disabled"
        elseif self.HoldActive then off = "hold order"
        elseif self.EscortEnt then off = "escort order"
        elseif _G.MercenariesDismissed then off = "dismissed"
        elseif _G.MercIdle then off = "idle"
        elseif not self.FormationLeader then off = "no leader"
        elseif (self.SquadSize or 0) < 2 then off = "squad under 2"
        end
        if off ~= self._formationOffReason then
            self._formationOffReason = off
            System.LogAlways(off
                and ('[MercForm] formation OFF (' .. off .. ') - squad is on the follow chain')
                or  '[MercForm] formation back ON')
        end
        if off then return end
        if not self:IsFormationEligible(nil, myWuid) then return end
        -- Per-merc, and deliberately AFTER the squad-wide reasons and out of the `off`
        -- chain: this one is true for the man standing inside the camp walls and false
        -- for his mate already marching away, so it can never be a single shared
        -- reason string. See NavSuppressFormationFor.
        --
        -- NEVER the leader, though. MakeFormation runs only inside follow.xml behind
        -- $isFormationLeader, so suppressing the ANCHOR means no formation object exists
        -- for anybody - every follower's GetMemberFormation comes back null and the whole
        -- squad drops to the follow chain, instead of just the men still inside the walls.
        -- He is what the shape hangs off; he is not steered by it. This is why a party
        -- deployed from a WALLED camp formed up nowhere: the leader is elected nearest the
        -- player, and the player is standing in his own camp when he gives the order.
        local isLeader = (tostring(self.FormationLeader) == tostring(myWuid))
        if not isLeader and self.NavSuppressFormationFor
           and self:NavSuppressFormationFor(myWuid) then return end

        bt_data.useFormation      = true
        bt_data.formationLeader   = self.FormationLeader
        bt_data.isFormationLeader = (tostring(self.FormationLeader) == tostring(myWuid))
        -- "" (set above) is the engine's own "any free spot", which is what everyone but
        -- a named companion keeps. See UpdateFormationFront.
        local front = (self.FormationFrontOf or {})[tostring(myWuid)]
        if front then bt_data.preferredSpot = front end
    end)
    if not ok then System.LogAlways('[MercForm] UpdateFormationRole Error: ' .. tostring(err)) end
end

-- Called by the leader's tree right after MakeFormation. Whether a mod's
-- whole-file override of FormationDefinitions.xml is honoured at all has never
-- been proven - nothing in the reference set overrides it, and it is read once at
-- AI-system init rather than lazily. If a name does not resolve the handle is
-- null, every follower's GetMemberFormation returns null, and they all drop to the
-- follow chain - which is the "they don't hold a formation, they just follow me in
-- a blob" report.
--
-- The verdict comes from $formationOk, which follow.xml computes with a BT
-- comparison against $__null. It must NOT be re-derived here: a _wuid never reads
-- back as nil across the Lua bridge (same reason `data.x = nil` cannot clear one),
-- so the old `bt_data.formationWUID ~= nil` test answered OK unconditionally and
-- this log line was worthless.
--
-- On a genuine null we do not just report it: the squad is dropped onto stock
-- vanilla presets, which are in the catalogue no matter what happened to ours. A
-- real formation in the wrong shape beats no formation at all.
mercenaries.FormationFallbackMisses = 2   -- consecutive nulls before falling back (one can be a rebuild race)

function mercenaries:FormationMade(bt_data)
    local ok   = (bt_data and bt_data.formationOk) == true
    local name = tostring(bt_data and bt_data.formationName)
    if ok ~= self._lastFormationOk or name ~= self._lastFormationName then
        self._lastFormationOk, self._lastFormationName = ok, name
        System.LogAlways(string.format('[MercForm] MakeFormation %s -> %s%s',
            name, ok and "OK" or "NULL HANDLE",
            ok and "" or "  <-- preset not found; squad falls back to the follow chain (a blob)"))
    end

    -- The control shape is the one case where a NULL HANDLE is the good answer, so
    -- spell the verdict out rather than leaving it to be inferred.
    if self.FormationShape == "control" then
        if self._controlLogged then return end
        self._controlLogged = true
        System.LogAlways(ok
            and '[MercForm] CONTROL: MakeFormation returned a handle for a name that exists NOWHERE. '
                .. 'A null handle is therefore not a usable signal, and the automatic vanilla fallback '
                .. 'can never fire - A/B merc_formation_vanilla by eye instead.'
            or  '[MercForm] CONTROL: null handle for a nonexistent name, as it should be. '
                .. 'Null-handle detection works, so an OK on a merc_* preset means the catalogue IS loaded.')
        System.LogAlways('[MercForm] control test done - run merc_formation_column (or any shape) to restore.')
        return
    end

    if ok then self._formationNullRun = 0 return end

    -- "vanilla" is already the fallback - it must not trigger another switch.
    if self.FormationShape == "vanilla" then return end

    -- The misses have to be against the SAME preset name. Counting any two
    -- consecutive Inits would let a load or a shape change - where the name is
    -- mid-flight - contribute a strike, and downgrade the whole session to stock
    -- presets over a startup race rather than a genuinely missing catalogue.
    if name ~= self._formationNullName then
        self._formationNullName = name
        self._formationNullRun  = 0
    end

    self._formationNullRun = (self._formationNullRun or 0) + 1
    if self._formationNullRun < self.FormationFallbackMisses then
        -- Nothing re-runs MakeFormation on its own - the owner branch only re-enters
        -- when the epoch changes - so waiting for a second opinion means asking for
        -- one. Without this bump the counter sits on one strike for ever and the
        -- fallback never fires. Bounded: at most FormationFallbackMisses-1 rebuilds.
        self.FormationEpoch = (self.FormationEpoch or 0) + 1
        return
    end
    self._formationNullRun = 0

    System.LogAlways('[MercForm] ' .. name .. ' does not resolve - the mod\'s FormationDefinitions.xml ' ..
                     'override is not in the loaded catalogue. Switching to stock vanilla presets so the ' ..
                     'squad marches in SOME formation; merc_formation_column etc. will re-arm ours.')
    self:SetFormationShape("vanilla", true)
end

-- ===== Controls =====
function mercenaries:SetFormationShape(key, silent)
    if key ~= "vanilla" and key ~= "control" then
        local known = false
        for _, k in ipairs(self.FormationShapeOrder) do
            if k == key then known = true break end
        end
        if not known then key = "column" end
    end
    -- Picking a shape by hand clears the null-handle streak: the automatic
    -- fallback must never fire off misses counted against a shape you have since
    -- replaced.
    self._formationNullRun = 0
    self._controlLogged    = false
    self.FormationShape = key
    -- Resolve the new preset name RIGHT HERE. Leaving FormationName nil for even one
    -- tick is a live bug: the per-merc updater runs on its own loop, sees nil, and
    -- falls back - and if the leader's branch re-enters in that window it calls
    -- MakeFormation with the fallback instead of the shape just picked. That is why
    -- only the first shape command used to work.
    self.FormationCap  = 0
    self.FormationName = self:FormationPresetName(math.max((self.SquadSize or 1) - 1, 0))
    self.FormationEpoch = (self.FormationEpoch or 0) + 1
    if not silent then Game.SendInfoText("@merc_n_form_shape @merc_form_" .. key, false, 0, 3) end
    System.LogAlways('[MercForm] shape = ' .. key .. ' preset=' .. tostring(self.FormationName))
end

-- Picking a mode by hand PINS it: the sprint-slack logic below would otherwise quietly
-- overwrite the choice a second later, which would look like the command not working.
function mercenaries:SetFormationMode(code)
    code = tonumber(code) or 1
    if not self.FormationModeNames[code] then code = 1 end
    self.FormationModeCode   = code
    self.FormationModePinned = true
    Game.SendInfoText("@merc_n_form_mode @" .. self.FormationModeLocKeys[code], false, 0, 3)
    System.LogAlways('[MercForm] mode = ' .. self.FormationModeNames[code] ..
                     ' (pinned; automatic sprint slack is now off)')
end

function mercenaries:SetFormationRelocate(on)
    self.FormationRelocate = on and true or false
    Game.SendInfoText("@merc_n_form_reloc @" .. (self.FormationRelocate and "merc_form_reloc_on" or "merc_form_reloc_off"), false, 0, 3)
    System.LogAlways('[MercForm] AllowRelocation = ' .. tostring(self.FormationRelocate))
end

-- Takes a REAL BOOLEAN, not a console string: the commands bake `true`/`false` into their
-- bodies (mercenaries_commands.lua) because %line substitution has proved unreliable here and
-- a toggle that silently no-ops is a debugging trap, not a feature.
function mercenaries:FormationEnabledSet(on)
    on = (on == true)
    if on == (self.FormationEnabled and true or false) then
        System.LogAlways('[MercForm] engine formation already ' .. (on and "ON" or "OFF"))
        self:FormationEnabledStatus()
        return
    end
    self.FormationEnabled = on
    -- Followers watch the epoch and the leader's subtree re-evaluates on it, so bumping makes
    -- the change land on the CURRENT squad within a tick instead of at the next rebuild.
    self.FormationEpoch = (self.FormationEpoch or 0) + 1
    System.LogAlways('[MercForm] engine formation ' ..
        (on and "ON" or "OFF - squad reverts to the plain CrimeFollower chain") ..
        ' (epoch ' .. tostring(self.FormationEpoch) .. ')')
    self:FormationEnabledStatus()
end

-- Proves whether the toggle actually took, and - when the formation is off for some OTHER
-- reason - names which one, so "the command did nothing" can never again be ambiguous.
function mercenaries:FormationEnabledStatus()
    local inSlot, followers = 0, 0
    for _, ent in pairs(self.ActiveMercs or {}) do
        local w = ent and (ent.this and ent.this.id or ent.id)
        if w and tostring(w) ~= tostring(self.FormationLeader) then
            followers = followers + 1
            if (self.FormationInSlot or {})[tostring(w)] then inSlot = inSlot + 1 end
        end
    end
    System.LogAlways(string.format(
        '[MercForm] FormationEnabled=%s  offReason=%s  leader=%s  inFormationSlot=%d/%d',
        tostring(self.FormationEnabled), tostring(self._formationOffReason or "none"),
        tostring(self.FormationLeader), inSlot, followers))
    if self.FormationEnabled and inSlot == 0 and followers > 0 then
        System.LogAlways('[MercForm] NOTE: nobody is in a slot even though it is enabled - ' ..
                         'the squad is ALREADY on the follow chain, so turning it off changes nothing.')
    end
end

function mercenaries:MonitorFormationTokens(p)
    local n = p:GetCountOfClass(self.TokenIDFormation)
    if n and n > 0 then
        p:DeleteItemOfClass(self.TokenIDFormation, n)
        local key = self.FormationShapeOrder[n]
        if key then self:SetFormationShape(key) end
    end
end

function mercenaries:FormationStatus()
    local leader = self.FormationLeader and tostring(self.FormationLeader) or nil
    local inSlot, followers = 0, 0
    -- Eligibility is decided per merc and is deliberately NOT logged per tick, so this
    -- is the only place it can be seen. It is the number that matters after a partial
    -- deploy: the out-party is supposed to be eligible and the men left in camp are not,
    -- and "eligible=0/8" says at a glance that the split did not take.
    local elig, total, camped, actor = 0, 0, 0, 0
    for _, ent in pairs(self.ActiveMercs or {}) do
        local w = ent and (ent.this and ent.this.id or ent.id)
        if w then
            total = total + 1
            if self:IsFormationEligible(ent, w) then elig = elig + 1 end
            if self.IsMercInCampProper and self:IsMercInCampProper(w) then camped = camped + 1 end
            if self.CampActorGet and self:CampActorGet(w) then actor = actor + 1 end
        end
        if w and tostring(w) ~= leader then
            followers = followers + 1
            if (self.FormationInSlot or {})[tostring(w)] then inSlot = inSlot + 1 end
        end
    end
    System.LogAlways(string.format(
        '[MercForm] shape=%s preset=%s mode=%s relocate=%s leader=%s epoch=%d squad=%d mounted=%s makeFormation=%s inFormation=%d/%d',
        tostring(self.FormationShape), tostring(self.FormationName),
        tostring(self.FormationModeNames[self.FormationModeCode or 1]),
        tostring(self.FormationRelocate), tostring(self.FormationLeader),
        self.FormationEpoch or 0, self.SquadSize or 0, tostring(self.FormationMounted),
        (self._lastFormationOk == nil) and "not-yet-run" or (self._lastFormationOk and "OK" or "NULL HANDLE"),
        inSlot, followers))
    local front = 0
    for _ in pairs(self.FormationFrontOf or {}) do front = front + 1 end
    local spotName, spotSlots = self:FormationFrontSpot()
    System.LogAlways(string.format(
        '[MercForm] eligible=%d/%d (in camp %d, camp actor %d) off=%s front=%d/%d spot=%s',
        elig, total, camped, actor, tostring(self._formationOffReason or "no"),
        front, spotSlots or 0, tostring(spotName or "-")))
    if followers > 0 and inSlot == 0 then
        System.LogAlways('[MercForm] NOBODY is in a formation slot - the squad is on the follow chain. ' ..
                         'If makeFormation says OK, run merc_formation_control: if THAT also says OK the ' ..
                         'engine returns a handle for any name and the preset catalogue is the problem.')
    end
end
