-- GENERATED by tools/measure_camp_props.py - do not edit by hand.
--
-- What every mesh the camp spawns actually measures, read out of the object paks. The camp
-- used to validate every tent against one hardcoded box on the stated grounds that the
-- variants "share the same footprint"; they do not, and the spread below is why tents came
-- out overlapping what the map had approved.
--
-- MESH SPACE, metres:
--   x, y    half-extents along the mesh's own X and Y axes
--   ox, oy  where that box's centre sits relative to the origin it is spawned at - three of
--           the tents are not centred on their own origin at all
--   tall    height above that origin
--
-- CampPropFootHalf in mercenaries_camp.lua turns these into the placement frame. Re-run the
-- tool after adding a model to CampModels, CampTentVariants, CampTentClutterVariants,
-- CampTrainingDummyModels, CampPlayerTentModel, CampFireOverlayModel or CampNightLightModel.

mercenaries.CampPropFoot = {
    ["objects/manmade/structures/living/tents/tent_small_shabby_a.cgf"] =                    { x = 1.57, y = 0.81, ox = 0.17, oy = 0.46, tall = 1.65 },
    ["objects/manmade/structures/living/tents/tent_small_forest_a.cgf"] =                    { x = 1.46, y = 1.19, ox = -0.05, oy = -0.02, tall = 1.82 },
    ["objects/manmade/common_furniture/beds/low/bed_shabby_a.cgf"] =                         { x = 0.53, y = 1.02, ox = -0.00, oy = -0.00, tall = 0.16 },
    ["objects/manmade/common_furniture/chairs/low/chair_rustic_d.cgf"] =                     { x = 0.23, y = 0.22, ox = -0.02, oy = 0.23, tall = 0.46 },
    ["objects/manmade/common_furniture/chairs/low/chair_trunk_c.cgf"] =                      { x = 0.16, y = 0.16, ox = 0.00, oy = 0.16, tall = 0.47 },
    ["objects/manmade/common_furniture/sacks/sack_b.cgf"] =                                  { x = 0.25, y = 0.26, ox = -0.01, oy = -0.01, tall = 0.52 },
    ["objects/manmade/common_furniture/chests/chest-small-a.cgf"] =                          { x = 0.17, y = 0.14, ox = 0.00, oy = -0.00, tall = 0.20 },
    ["objects/manmade/common_decorations/weapons/polearm_pile_a.cgf"] =                      { x = 0.41, y = 0.42, ox = 0.09, oy = 0.07, tall = 2.11 },
    ["objects/manmade/structures/living/tents/tent_small_forest_b.cgf"] =                    { x = 1.83, y = 0.92, ox = 0.39, oy = 0.44, tall = 1.89 },
    ["objects/manmade/structures/living/tents/tent_small_forest_d.cgf"] =                    { x = 2.12, y = 1.42, ox = 0.19, oy = 0.69, tall = 2.04 },
    ["objects/manmade/structures/living/tents/tent_small_rustic_a.cgf"] =                    { x = 2.33, y = 1.53, ox = 0.12, oy = 0.10, tall = 2.13 },
    ["objects/manmade/common_furniture/sacks/sack_pig_feed.cgf"] =                           { x = 0.25, y = 0.35, ox = 0.00, oy = 0.00, tall = 0.60 },
    ["objects/manmade/common_furniture/sacks/sack_charcoal.cgf"] =                           { x = 0.32, y = 0.24, ox = -0.02, oy = -0.01, tall = 0.53 },
    ["objects/manmade/common_furniture/crates/crate_low_b.cgf"] =                            { x = 0.30, y = 0.51, ox = 0.02, oy = 0.03, tall = 0.41 },
    ["objects/manmade/common_furniture/crates/crate_small.cgf"] =                            { x = 0.22, y = 0.22, ox = -0.00, oy = 0.01, tall = 0.44 },
    ["objects/manmade/task_specific_props/combat/archery/target_straw.cgf"] =                { x = 0.72, y = 0.23, ox = -0.02, oy = 0.05, tall = 1.97 },
    ["objects/manmade/task_specific_props/combat/archery/target_stand.cgf"] =                { x = 0.51, y = 0.47, ox = -0.00, oy = 0.45, tall = 2.03 },
    ["objects/manmade/structures/living/tents/tent_big_round_a.cgf"] =                       { x = 2.26, y = 2.22, ox = -0.00, oy = -0.04, tall = 5.26 },
    ["objects/manmade/task_specific_props/food_processing/cooking/camp_cooking_c_old.cgf"] = { x = 0.97, y = 0.94, ox = 0.08, oy = 0.06, tall = 1.99 },
    ["objects/manmade/common_illumination/lamp_table_rustic_a.cgf"] =                        { x = 0.12, y = 0.13, ox = -0.00, oy = -0.01, tall = 0.07 },
}
