-- Squad formation: which shape the squad marches in, who anchors it, and when it
-- gets rebuilt. The behaviour-tree half is the two ENGINE FORMATION arms plus the
-- formation-owner loop in data/AI/follow.xml. Full write-up: docs/formations.md.
--
-- The engine anchors a formation on whatever entity ran MakeFormation, and the
-- player has no behaviour tree, so one merc is elected to stand in for him: he
-- follows the player, and everyone else FormationFollowers off him. Shapes are
-- authored so nothing ever sits ahead of that leader, which keeps the player at
-- the head of his own squad.
--
-- Shapes live in data/AI/FormationDefinitions.xml, generated by
-- tools/gen_formations.py. That file is a WHOLE-FILE override of the vanilla
-- catalogue - it is not a patchable database table, so there is no merge - and it
-- re-lists all 63 vanilla formations verbatim. Regenerate it after a game update.
--
-- Everything here is deliberately latched. Every earlier version churned:
-- re-electing each tick, re-resolving the preset from a live headcount, or gating
-- on a heartbeat. Each of those rebuilt the formation, and a rebuild makes every
-- follower re-join into a newly assigned spot - which reads as the whole squad
-- milling about. FormationEpoch is the rebuild signal, and nothing bumps it
-- without a reason it can name in the log.

mercenaries.FormationShapeOrder = { "column", "line", "square", "wedge", "circle", "escort" }
mercenaries.FormationShape = "column"

-- Sizes generated per shape. Lua picks the smallest that seats the squad: handing a
-- 50-slot template to six mercs lets the engine drop them in any six of fifty spots
-- and strings them out over the whole template.
-- Steps are deliberately close together - under KeepShape a spot's pose is a rigid
-- rotation about the anchor, so a spot d metres out swings 2*d*sin(theta/2) when the
-- leader turns, and a ladder that jumps 60% in one step jumps that lever arm with it.
mercenaries.FormationSizes = { 6, 10, 14, 18, 24, 30, 40, 50 }

mercenaries.FormationLeader   = nil
mercenaries.FormationEpoch    = 0
mercenaries.FormationName     = nil
mercenaries.FormationCap      = 0
mercenaries.FormationMounted  = nil
mercenaries.SquadSize         = 0
mercenaries.FormationTickMs   = 150

-- How far behind the front-runner the sitting leader must fall before leadership
-- is handed over. Distance ordering churns every step as the squad walks, and each
-- handover rebuilds the formation, so this has to be a real gap and not a tie-break.
-- Mounted needs far more room: the mounted preset is ~64m deep, riders overtake
-- constantly, and at 8m the leader changed every few seconds - the formation was
-- rebuilt so often it never settled, which is what read as "mounted mercs take
-- ages to start following".
mercenaries.FormationLeaderSwapMargin        = 8.0
mercenaries.FormationLeaderSwapMarginMounted = 30.0
-- ...and the challenger must HOLD that lead this long, so one overtake on a corner
-- is not a handover.
mercenaries.FormationLeaderSwapSecs     = 3.0
-- ...and after any swap, no further displacement swap for this long, so a rebuild
-- always gets time to settle.
mercenaries.FormationLeaderSwapCooldown = 6.0

-- KeepShape on foot: it is the only mode that holds an authored shape. Relaxed
-- drifts and MoveHistory replays the leader's path, so both blur the geometry.
-- Mounted overrides this to MoveHistory in follow.xml - no vanilla mounted
-- formation uses KeepShape, and rigid geometry is not something a horse can hold.
mercenaries.FormationModeCode = 1
mercenaries.FormationRelocate = false
mercenaries.FormationModeNames = { [0] = "Relaxed", [1] = "KeepShape", [2] = "MoveHistory" }

-- Formation shape chosen from dialogue. Count-encoded on one token the way the
-- archer stance is: the quest grants Amount = N and N indexes FormationShapeOrder,
-- so six shapes need one item class instead of six. Fed by both the E-dialog and
-- the silent order wheel.
mercenaries.TokenIDFormation = "679a655e-189d-4519-b437-ccc4b92be51d"

-- Build a preset name guaranteed to exist in FormationDefinitions.xml. NEVER
-- hardcode one: the size ladder has changed several times, and a name carrying a
-- size that is no longer generated resolves to nothing, MakeFormation returns a
-- null handle, and the squad silently drops to the follow chain - which looks like
-- a column and is indistinguishable from the formation system being broken.
function mercenaries:FormationPresetName(size)
    if self.FormationShape == "vanilla" then
        return ((size or 0) <= 8) and "followNPC" or "infantryMen20"
    end
    local pick = self.FormationSizes[#self.FormationSizes]
    for _, n in ipairs(self.FormationSizes) do
        if (size or 0) <= n then pick = n break end
    end
    -- Mounted has exactly one shape: a triple column at horse spacing. The infantry
    -- shapes assume a 2m footprint and a body that can turn on the spot; a horse
    -- needs 3.5m files, 4m ranks, and corners wide.
    local shape = _G.PlayerMounted and "mounted" or self.FormationShape
    return "merc_" .. shape .. tostring(pick)
end

-- Once per FormationTickMs. Picks the leader and the preset, and bumps the epoch
-- only when something real changed.
function mercenaries:UpdateFormationLeader()
    local pp
    pcall(function() pp = player and player:GetWorldPos() end)

    local best, bestD, count = nil, nil, 0
    local leaderStillOk, leaderD = false, nil

    for _, ent in pairs(self.ActiveMercs) do
        local wuid = ent and (ent.this and ent.this.id or ent.id)
        if self:IsFormationEligible(ent, wuid) and not self:IsCampActor(wuid) then
            count = count + 1

            -- NEAREST to the player leads. The formation hangs off the leader, so
            -- if he is buried inside the pack the whole shape is anchored in the
            -- middle of a crowd he cannot walk out of - at 50 mercs that turns the
            -- squad into a shapeless mass that stops tracking the player at all.
            -- Whoever is closest to the player is by definition on the outside of
            -- the mass, facing the way it needs to go.
            local d = 0
            if pp then
                local mp = ent:GetPos()
                if mp then
                    local dx, dy = pp.x - mp.x, pp.y - mp.y
                    d = math.sqrt(dx * dx + dy * dy)
                end
            end

            if self.FormationLeader and tostring(wuid) == tostring(self.FormationLeader) then
                leaderStillOk, leaderD = true, d
            end
            if not bestD or d < bestD then best, bestD = wuid, d end
        end
    end

    self.SquadSize = count

    local reason = nil

    -- Hysteresis, in THREE parts. Every leader change runs EndFormation +
    -- MakeFormation and forces every follower to re-acquire a slot, so a swap is
    -- expensive and must be rare. Distance alone was not enough: this runs every
    -- 150ms, and mounted riders overtake each other constantly, which produced
    -- "leader displaced" rebuilds in a steady stream - the squad never settled
    -- long enough to form up, which is what "mounted mercs take ages to follow"
    -- actually was.
    --   1. margin   - the challenger must be clearly ahead, and MUCH clearer when
    --                 mounted, because the mounted preset is ~64m deep and being
    --                 20m ahead of the leader is normal, not exceptional.
    --   2. duration - he must hold that lead continuously, so a momentary overtake
    --                 while cornering is ignored.
    --   3. cooldown - no second swap straight after one, so a rebuild always gets
    --                 time to actually settle before another can start.
    -- A leader who is dead or no longer eligible is replaced IMMEDIATELY: that is
    -- not churn, and none of the three apply to it.
    local now = 0
    pcall(function() now = System.GetCurrTime() or 0 end)

    local mounted = _G.PlayerMounted and true or false
    local margin  = mounted and self.FormationLeaderSwapMarginMounted
                            or  self.FormationLeaderSwapMargin

    local ahead = leaderStillOk and bestD and leaderD
                  and (leaderD - bestD) > margin
                  and tostring(best or '') ~= tostring(self.FormationLeader or '')

    if ahead then
        -- Restart the clock whenever the challenger changes, so the timer only ever
        -- measures ONE man holding the lead.
        if tostring(self._leadChallenger or '') ~= tostring(best or '') then
            self._leadChallenger  = best
            self._leadChallengeAt = now
        end
    else
        self._leadChallenger, self._leadChallengeAt = nil, nil
    end

    local held    = ahead and self._leadChallengeAt
                    and (now - self._leadChallengeAt) >= self.FormationLeaderSwapSecs
    local cooling = self._leadSwapAt
                    and (now - self._leadSwapAt) < self.FormationLeaderSwapCooldown

    if not leaderStillOk then
        if tostring(best or '') ~= tostring(self.FormationLeader or '') then reason = "leader" end
        self.FormationLeader = best
        self._leadSwapAt = now
        self._leadChallenger, self._leadChallengeAt = nil, nil
    elseif held and not cooling then
        reason = "leader displaced"
        self.FormationLeader = best
        self._leadSwapAt = now
        self._leadChallenger, self._leadChallengeAt = nil, nil
    end

    local followers = math.max(count - 1, 0)
    local cap = self.FormationCap or 0

    -- Mounting swaps the whole shape (infantry spacing -> horse spacing), so it has
    -- to defeat the grow-only latch below. This is a real state change, not the
    -- eligibility noise the latch exists to absorb.
    local mounted = _G.PlayerMounted and true or false
    if mounted ~= self.FormationMounted then
        self.FormationMounted = mounted
        self.FormationName = nil
        self.FormationCap = 0
        cap = 0
        reason = reason or (mounted and "mounted" or "dismounted")
    end

    -- Grows immediately; shrinks only once the squad is clearly inside the next size
    -- down, so hovering on a boundary cannot oscillate. Without any shrink at all, a
    -- squad that peaks at 24 and then loses 8 keeps the 24-spot template and
    -- scatters the survivors across it.
    local want = nil
    if followers > cap or not self.FormationName then
        want = self.FormationSizes[#self.FormationSizes]
        for _, n in ipairs(self.FormationSizes) do
            if followers <= n then want = n break end
        end
    else
        local smaller = nil
        for _, n in ipairs(self.FormationSizes) do
            if n < cap then smaller = n end
        end
        if smaller and followers <= (smaller - 2) then want = smaller end
    end

    if want then
        local name = self:FormationPresetName(want)
        if name ~= self.FormationName then
            reason = reason or ((want > cap) and "grow" or "shrink")
            self.FormationName = name
            self.FormationCap  = want
        end
    end

    if reason then
        self.FormationEpoch = (self.FormationEpoch or 0) + 1
        System.LogAlways(string.format('[MercForm] rebuild #%d (%s) preset=%s leader=%s',
            self.FormationEpoch, reason, tostring(self.FormationName), tostring(self.FormationLeader)))
    end
end

-- NO AUTOMATIC FORMATION-MODE SWITCHING. This was tried as "sprint relief" - KeepShape while
-- walking, MoveHistory while the player sprints - and it is a trap in a DEEP formation.
--
-- merc_column50 is 45m from front spot to back spot. KeepShape places that back spot as a
-- rigid offset behind the leader's facing; MoveHistory places it 45m back along the path he
-- actually walked. After any turn those are two completely different points, tens of metres
-- apart, so every mode switch teleported each follower's TARGET and the man ran off to it -
-- the "everyone except the leader runs 20m away and then comes back" bug. It fired exactly
-- when the player's speed crossed the threshold, i.e. whenever he got a little ahead.
--
-- The keep-up problem it was meant to solve is handled properly by the merc_keepup_buff
-- (rms*1.3): make the followers faster, do not move the goalposts. Leave the mode alone.

-- ---------------------------------------------------------------------------
-- Follow spread diagnostic: merc_follow_stats 1
--
-- Answers "are they keeping up, and who is not" with numbers rather than impressions.
-- Logs the player's measured speed, whether the formation is loosened, and the SPREAD of
-- the squad's distance to the player (nearest / median / worst) plus how many are past the
-- teleport line. A healthy column has a stable median and a worst that does not climb.
-- ---------------------------------------------------------------------------
mercenaries.FollowStats = false
mercenaries.FollowStatsEvery = 2.0

function mercenaries:FollowStatsSet(v)
    self.FollowStats = (tostring(v or ''):match('1') ~= nil)
    System.LogAlways('[MercSpread] logging ' .. (self.FollowStats and 'ON' or 'OFF'))
end

function mercenaries:FollowStatsTick()
    if not self.FollowStats then return end
    local now = 0
    pcall(function() now = System.GetCurrTime() or 0 end)
    if self._fsAt and (now - self._fsAt) < self.FollowStatsEvery then return end
    self._fsAt = now

    pcall(function()
        local pp = player and player:GetWorldPos()
        if not pp then return end
        local gate = (self.TeleportDistance and self:TeleportDistance()) or 50.0
        local d, far = {}, 0
        for _, ent in pairs(self.ActiveMercs or {}) do
            local mp = ent:GetWorldPos()
            if mp then
                local dx, dy = pp.x - mp.x, pp.y - mp.y
                local v = math.sqrt(dx * dx + dy * dy)
                table.insert(d, v)
                if v > gate then far = far + 1 end
            end
        end
        if #d == 0 then return end
        table.sort(d)

        -- Epoch, mode and leader are logged because they are the three things that can move a
        -- follower's TARGET rather than the follower: a formation rebuild, a mode change, or a
        -- new anchor. If the spread jumps on the same tick one of these changes, the squad is
        -- chasing a moved goalpost, not failing to keep up.
        System.LogAlways(string.format(
            '[MercSpread] pSpeed=%.1f n=%d near=%.1f med=%.1f worst=%.1f beyondGate=%d | epoch=%d mode=%d preset=%s',
            self.PlayerSpeed or 0, #d,
            d[1], d[math.ceil(#d / 2)], d[#d], far,
            self.FormationEpoch or 0, self.FormationModeCode or 1,
            tostring(self.FormationName)))
    end)
end

System.AddCCommand("merc_follow_stats", "mercenaries:FollowStatsSet('%line')",
                   "Log squad spread and player speed: merc_follow_stats 1 | 0")

function mercenaries.FormationLoop()
    local ok, err = pcall(function()
        if next(mercenaries.ActiveMercs) and player then
            mercenaries:UpdateFormationLeader()
            mercenaries:FollowStatsTick()
        end
    end)
    if not ok then System.LogAlways('[MercForm] FormationLoop Error: ' .. tostring(err)) end
    Script.SetTimerForFunction(mercenaries.FormationTickMs, "mercenaries.FormationLoop")
end

-- Per merc, from follow.xml's updater loop.
function mercenaries:UpdateFormationRole(bt_data, myWuid)
    local ok, err = pcall(function()
        bt_data.useFormation      = false
        bt_data.isFormationLeader = false
        bt_data.formationEpoch    = self.FormationEpoch or 0
        bt_data.formationModeCode = self.FormationModeCode or 1
        bt_data.formationRelocate = self.FormationRelocate or false
        -- Derived, never hardcoded, so it always names a preset that exists for the
        -- current shape and ladder.
        bt_data.formationName     = self.FormationName
                                    or self:FormationPresetName(math.max((self.SquadSize or 1) - 1, 0))

        -- A walled camp is the one place the formation cannot be steered around an
        -- obstacle, so it stands down and the merc falls back to the follow chain.
        if self.NavSuppressFormation and self:NavSuppressFormation() then return end
        if _G.MercenariesDismissed or _G.MercIdle then return end
        if not self.FormationLeader then return end
        if not self:IsFormationEligible(nil, myWuid) then return end
        if self:IsCampActor(myWuid) then return end
        if (self.SquadSize or 0) < 2 then return end

        bt_data.useFormation      = true
        bt_data.formationLeader   = self.FormationLeader
        bt_data.isFormationLeader = (tostring(self.FormationLeader) == tostring(myWuid))
    end)
    if not ok then System.LogAlways('[MercForm] UpdateFormationRole Error: ' .. tostring(err)) end
end

-- Called by the leader's tree right after MakeFormation. Whether a mod's
-- whole-file override of FormationDefinitions.xml is honoured at all has never
-- been proven - nothing in the reference set overrides it, and it is read once at
-- AI-system init rather than lazily. If a name does not resolve the handle is
-- null, every follower's GetMemberFormation returns null, and they all drop to the
-- follow chain. Logged on change only, so it costs nothing while it is working.
function mercenaries:FormationMade(bt_data)
    local ok = bt_data and bt_data.formationWUID ~= nil
    local name = tostring(bt_data and bt_data.formationName)
    if ok ~= self._lastFormationOk or name ~= self._lastFormationName then
        self._lastFormationOk, self._lastFormationName = ok, name
        System.LogAlways(string.format('[MercForm] MakeFormation %s -> %s%s',
            name, ok and "OK" or "NULL HANDLE",
            ok and "" or "  <-- preset not found; squad falls back to the follow chain (a column)"))
    end
end

-- ===== Controls =====
function mercenaries:SetFormationShape(key)
    if key ~= "vanilla" then
        local known = false
        for _, k in ipairs(self.FormationShapeOrder) do
            if k == key then known = true break end
        end
        if not known then key = "column" end
    end
    self.FormationShape = key
    -- Resolve the new preset name RIGHT HERE. Leaving FormationName nil for even one
    -- tick is a live bug: the per-merc updater runs on its own loop, sees nil, and
    -- falls back - and if the leader's branch re-enters in that window it calls
    -- MakeFormation with the fallback instead of the shape just picked. That is why
    -- only the first shape command used to work.
    self.FormationCap  = 0
    self.FormationName = self:FormationPresetName(math.max((self.SquadSize or 1) - 1, 0))
    self.FormationEpoch = (self.FormationEpoch or 0) + 1
    Game.SendInfoText("Formation: " .. key, false, 0, 3)
    System.LogAlways('[MercForm] shape = ' .. key .. ' preset=' .. tostring(self.FormationName))
end

-- Picking a mode by hand PINS it: the sprint-slack logic below would otherwise quietly
-- overwrite the choice a second later, which would look like the command not working.
function mercenaries:SetFormationMode(code)
    code = tonumber(code) or 1
    if not self.FormationModeNames[code] then code = 1 end
    self.FormationModeCode   = code
    self.FormationModePinned = true
    Game.SendInfoText("Mode: " .. self.FormationModeNames[code], false, 0, 3)
    System.LogAlways('[MercForm] mode = ' .. self.FormationModeNames[code] ..
                     ' (pinned; automatic sprint slack is now off)')
end

function mercenaries:SetFormationRelocate(on)
    self.FormationRelocate = on and true or false
    Game.SendInfoText("Relocation: " .. tostring(self.FormationRelocate), false, 0, 3)
    System.LogAlways('[MercForm] AllowRelocation = ' .. tostring(self.FormationRelocate))
end

function mercenaries:MonitorFormationTokens(p)
    local n = p:GetCountOfClass(self.TokenIDFormation)
    if n and n > 0 then
        p:DeleteItemOfClass(self.TokenIDFormation, n)
        local key = self.FormationShapeOrder[n]
        if key then self:SetFormationShape(key) end
    end
end

function mercenaries:FormationStatus()
    System.LogAlways(string.format(
        '[MercForm] shape=%s preset=%s mode=%s relocate=%s leader=%s epoch=%d squad=%d mounted=%s',
        tostring(self.FormationShape), tostring(self.FormationName),
        tostring(self.FormationModeNames[self.FormationModeCode or 1]),
        tostring(self.FormationRelocate), tostring(self.FormationLeader),
        self.FormationEpoch or 0, self.SquadSize or 0, tostring(self.FormationMounted)))
end
