$ErrorActionPreference = "Stop"

$locDir = Join-Path $PSScriptRoot "..\localization"
[xml]$source = Get-Content (Join-Path $locDir "English_xml.xml") -Raw -Encoding UTF8

$common = @{
  Polish_xml = @{
    "I want to hire some mercenaries." = "Chcę wynająć najemników."
    "I can get you some regular sellswords, or I have some specific companions available. What are you looking for?" = "Mogę załatwić ci zwykłych najemnych zbrojnych albo kilku konkretnych towarzyszy. Czego szukasz?"
    "Normal mercenaries." = "Zwykli najemnicy."
    "Just standard mercenaries." = "Po prostu zwykli najemnicy."
    "Custom companions." = "Wybrani towarzysze."
    "I'm looking for some specific people." = "Szukam konkretnych ludzi."
    "Ah, the special roster. Who do you have in mind?" = "Ach, specjalna lista. Kogo masz na myśli?"
    "The weakest (50 groschen)." = "Najsłabsi (50 groszy)."
    "Some decent lads (100 groschen)." = "Całkiem porządni chłopcy (100 groszy)."
    "An experienced Soldier (300 groschen)." = "Doświadczony żołnierz (300 groszy)."
    "Just one." = "Tylko jeden."
    "Two." = "Dwóch."
    "Three." = "Trzech."
    "There are some lads that are willing to help. How strong should they be?" = "Jest paru chłopaków gotowych pomóc. Jak silni mają być?"
    "The weakest will do." = "Najsłabsi wystarczą."
    "Alright, 50 groschen a head. How many do you need?" = "Dobrze, 50 groszy od głowy. Ilu potrzebujesz?"
    "Some decent lads." = "Całkiem porządni chłopcy."
    "Alright, 100 groschen a head. How many do you need?" = "Dobrze, 100 groszy od głowy. Ilu potrzebujesz?"
    "An experienced Soldier." = "Doświadczony żołnierz."
    "Top quality. That's 300 groschen a head. How many do you need?" = "Najwyższa jakość. To 300 groszy od głowy. Ilu potrzebujesz?"
    "I'll take two." = "Wezmę dwóch."
    "Give me three of them." = "Daj mi trzech."
    "Wait here for me." = "Poczekajcie tu na mnie."
    "Follow me." = "Za mną."
    "I'd like to dismiss all of you." = "Chcę was wszystkich odprawić."
    "As you say, boss." = "Jak sobie życzysz, szefie."
    "Right behind you." = "Tuż za tobą."
    "You're all dismissed." = "Wszyscy jesteście zwolnieni."
    "Bye bye." = "Żegnajcie."
    "Mercenary hired." = "Najemnik wynajęty."
    "Mercenaries hired." = "Najemnicy wynajęci."
    "Not enough groschen!" = "Za mało groszy!"
    "You have too many men already! Maximum of 5." = "Masz już zbyt wielu ludzi! Maksymalnie 5."
    "All mercenaries dismissed." = "Wszyscy najemnicy odprawieni."
    "Mercenaries waiting." = "Najemnicy czekają."
    "Mercenaries following." = "Najemnicy podążają za tobą."
    "Special companion hired." = "Specjalny towarzysz wynajęty."
    "This companion is already in your service!" = "Ten towarzysz już jest w twojej służbie!"
    "Mercenary" = "Najemnik"
    "Change Equipment..." = "Zmień wyposażenie..."
    "I need you to change your gear." = "Musisz zmienić ekwipunek."
    "What should we wear?" = "Co mamy założyć?"
    "Generic Mercenaries" = "Zwykli najemnicy"
    "Put on your usual gear." = "Załóżcie swoje zwykłe wyposażenie."
    "We'll change right away." = "Zmienimy się od razu."
    "Bandits" = "Bandyci"
    "Dress like bandits." = "Ubierzcie się jak bandyci."
    "I hope this doesn't land us in prison." = "Mam nadzieję, że nie skończymy przez to w więzieniu."
    "Cumans" = "Kumanowie"
    "Put on Cuman armor." = "Załóżcie kumańską zbroję."
    "Wear the colors of Skalitz and Leipa." = "Noście barwy Skalicy i Leipy."
    "For Sir Radzig!" = "Za pana Radziga!"
    "Wear the Kuttenberg colors." = "Noście barwy Kuttenbergu."
    "Right away." = "Od razu."
    "Wear the Skalitz colors, for old times' sake." = "Noście barwy Skalicy, przez wzgląd na dawne czasy."
    "For Skalitz, and for you, Henry." = "Za Skalicę i za ciebie, Henryku."
    "(Nevermind)" = "(Nieważne)"
    "Actually, nevermind." = "Właściwie nieważne."
    "Change combat stance..." = "Zmień nastawienie bojowe..."
    "I want to talk tactics." = "Chcę porozmawiać o taktyce."
    "How do you want us to fight?" = "Jak mamy walczyć?"
    "Attack anyone hostile, don't wait for me." = "Atakujcie każdego wroga, nie czekajcie na mnie."
    "Understood. We'll take the fight to them." = "Zrozumiano. Ruszymy na nich."
    "Only attack whoever I'm fighting." = "Atakujcie tylko tego, z kim ja walczę."
    "Got it, we'll follow your lead." = "Jasne, będziemy iść za twoim przykładem."
    "Only defend yourselves if attacked." = "Brońcie się tylko, jeśli was zaatakują."
    "Fair enough, we'll hold back." = "W porządku, będziemy się trzymać z tyłu."
    "Don't fight at all, no matter what." = "Nie walczcie wcale, bez względu na wszystko."
    "If you say so... let's hope it doesn't come to that." = "Skoro tak mówisz... miejmy nadzieję, że do tego nie dojdzie."
    "Mercenaries: attack everyone hostile." = "Najemnicy: atakują każdego wroga."
    "Mercenaries: attack whoever you attack." = "Najemnicy: atakują tego, kogo ty atakujesz."
    "Mercenaries: defend themselves only." = "Najemnicy: tylko się bronią."
    "Mercenaries: passive, won't fight." = "Najemnicy: pasywni, nie będą walczyć."
    "Change weapon loadout..." = "Zmień uzbrojenie..."
    "I want to talk about your weapons." = "Chcę porozmawiać o waszej broni."
    "What should we carry?" = "Co mamy nosić?"
    "Whatever's on hand." = "Cokolwiek jest pod ręką."
    "Suits us fine." = "Nam pasuje."
    "Sword and shield." = "Miecz i tarcza."
    "Arm yourselves with sword and shield." = "Uzbrójcie się w miecz i tarczę."
    "A sound choice." = "Rozsądny wybór."
    "Axe and shield." = "Topór i tarcza."
    "Take up axe and shield." = "Weźcie topór i tarczę."
    "Sturdy enough." = "Dość solidnie."
    "Longsword." = "Długi miecz."
    "Wield longswords, both hands free of a shield." = "Walczcie długimi mieczami, obiema rękami bez tarczy."
    "Room to swing, good." = "Jest miejsce na zamach, dobrze."
    "Mace and shield." = "Buzdygan i tarcza."
    "Carry mace and shield." = "Noście buzdygan i tarczę."
    "Bone-breaker's choice." = "Wybór do łamania kości."
    "Shortsword." = "Krótki miecz."
    "Keep it quick with a shortsword." = "Postawcie na szybkość z krótkim mieczem."
    "Light and fast, understood." = "Lekko i szybko, zrozumiano."
    "Mace." = "Buzdygan."
    "Take up the mace." = "Weźcie buzdygan."
    "Nothing like a good bludgeoning." = "Nie ma to jak porządne okładanie."
    "Axe." = "Topór."
    "Arm yourselves with axes." = "Uzbrójcie się w topory."
    "Sharp enough to split kindling, or skulls." = "Dość ostre, by rąbać szczapy albo czaszki."
    "Polearm." = "Broń drzewcowa."
    "Carry polearms." = "Noście broń drzewcową."
    "Keeps them at a distance, good." = "Trzyma ich na dystans, dobrze."
    "Your mercenaries are on their way." = "Twoi najemnicy są w drodze."
    "Recall my men." = "Przywołaj moich ludzi."
    "Send word to my men. I need them back." = "Przekażcie wiadomość moim ludziom. Potrzebuję ich z powrotem."
    "Consider it done. I'll send a runner right away." = "Uznaj to za zrobione. Zaraz wyślę gońca."
    "Patch yourselves up." = "Opatrzcie się."
    "Take these supplies and patch yourselves up. You look terrible." = "Weźcie te zapasy i opatrzcie się. Wyglądacie strasznie."
    "We'll do what we can, boss, but a proper healer wouldn't go amiss." = "Zrobimy, co się da, szefie, ale prawdziwy medyk by nie zaszkodził."
    "Your mercenaries have been healed." = "Twoi najemnicy zostali wyleczeni."
    "This is a test. I like cheese." = "To jest test. Lubię ser."
  }
  Portuguese_xml = @{
    "I want to hire some mercenaries." = "Quero contratar alguns mercenários."
    "Normal mercenaries." = "Mercenários normais."
    "Custom companions." = "Companheiros personalizados."
    "Just one." = "Só um."
    "Two." = "Dois."
    "Three." = "Três."
    "Wait here for me." = "Esperem aqui por mim."
    "Follow me." = "Sigam-me."
    "Mercenary hired." = "Mercenário contratado."
    "Mercenaries hired." = "Mercenários contratados."
    "Not enough groschen!" = "Groschen insuficientes!"
    "Mercenary" = "Mercenário"
    "Change Equipment..." = "Mudar equipamento..."
    "Bandits" = "Bandidos"
    "Cumans" = "Cumanos"
    "(Nevermind)" = "(Esquece)"
    "Actually, nevermind." = "Na verdade, esquece."
    "Sword and shield." = "Espada e escudo."
    "Axe and shield." = "Machado e escudo."
    "Longsword." = "Espada longa."
    "Mace and shield." = "Maça e escudo."
    "Shortsword." = "Espada curta."
    "Mace." = "Maça."
    "Axe." = "Machado."
    "Polearm." = "Arma de haste."
    "Your mercenaries have been healed." = "Os teus mercenários foram curados."
    "This is a test. I like cheese." = "Isto é um teste. Gosto de queijo."
  }
  Spanish_xml = @{
    "I want to hire some mercenaries." = "Quiero contratar algunos mercenarios."
    "Normal mercenaries." = "Mercenarios normales."
    "Custom companions." = "Compañeros personalizados."
    "Just one." = "Solo uno."
    "Two." = "Dos."
    "Three." = "Tres."
    "Wait here for me." = "Esperadme aquí."
    "Follow me." = "Seguidme."
    "Mercenary hired." = "Mercenario contratado."
    "Mercenaries hired." = "Mercenarios contratados."
    "Not enough groschen!" = "¡No hay suficientes groschen!"
    "Mercenary" = "Mercenario"
    "Change Equipment..." = "Cambiar equipo..."
    "Bandits" = "Bandidos"
    "Cumans" = "Cumanos"
    "(Nevermind)" = "(No importa)"
    "Actually, nevermind." = "En realidad, no importa."
    "Sword and shield." = "Espada y escudo."
    "Axe and shield." = "Hacha y escudo."
    "Longsword." = "Espada larga."
    "Mace and shield." = "Maza y escudo."
    "Shortsword." = "Espada corta."
    "Mace." = "Maza."
    "Axe." = "Hacha."
    "Polearm." = "Arma de asta."
    "Your mercenaries have been healed." = "Tus mercenarios han sido curados."
    "This is a test. I like cheese." = "Esto es una prueba. Me gusta el queso."
  }
  Ukrainian_xml = @{
    "I want to hire some mercenaries." = "Я хочу найняти кількох найманців."
    "Normal mercenaries." = "Звичайні найманці."
    "Custom companions." = "Особливі супутники."
    "Just one." = "Лише одного."
    "Two." = "Двох."
    "Three." = "Трьох."
    "Wait here for me." = "Чекайте мене тут."
    "Follow me." = "Ідіть за мною."
    "Mercenary hired." = "Найманця найнято."
    "Mercenaries hired." = "Найманців найнято."
    "Not enough groschen!" = "Недостатньо грошей!"
    "Mercenary" = "Найманець"
    "Change Equipment..." = "Змінити спорядження..."
    "Bandits" = "Бандити"
    "Cumans" = "Кумани"
    "(Nevermind)" = "(Неважливо)"
    "Actually, nevermind." = "Власне, неважливо."
    "Sword and shield." = "Меч і щит."
    "Axe and shield." = "Сокира і щит."
    "Longsword." = "Довгий меч."
    "Mace and shield." = "Булава і щит."
    "Shortsword." = "Короткий меч."
    "Mace." = "Булава."
    "Axe." = "Сокира."
    "Polearm." = "Держакова зброя."
    "Your mercenaries have been healed." = "Твої найманці зцілені."
    "This is a test. I like cheese." = "Це тест. Я люблю сир."
  }
  Vietnamese_xml = @{
    "I want to hire some mercenaries." = "Tôi muốn thuê vài lính đánh thuê."
    "Normal mercenaries." = "Lính đánh thuê thường."
    "Custom companions." = "Bạn đồng hành riêng."
    "Just one." = "Chỉ một."
    "Two." = "Hai."
    "Three." = "Ba."
    "Wait here for me." = "Đợi tôi ở đây."
    "Follow me." = "Theo tôi."
    "Mercenary hired." = "Đã thuê lính đánh thuê."
    "Mercenaries hired." = "Đã thuê các lính đánh thuê."
    "Not enough groschen!" = "Không đủ groschen!"
    "Mercenary" = "Lính đánh thuê"
    "Change Equipment..." = "Đổi trang bị..."
    "Bandits" = "Bọn cướp"
    "Cumans" = "Người Cuman"
    "(Nevermind)" = "(Thôi bỏ đi)"
    "Actually, nevermind." = "Thật ra, thôi bỏ đi."
    "Sword and shield." = "Kiếm và khiên."
    "Axe and shield." = "Rìu và khiên."
    "Longsword." = "Trường kiếm."
    "Mace and shield." = "Chùy và khiên."
    "Shortsword." = "Kiếm ngắn."
    "Mace." = "Chùy."
    "Axe." = "Rìu."
    "Polearm." = "Vũ khí cán dài."
    "Your mercenaries have been healed." = "Lính đánh thuê của anh đã được chữa lành."
    "This is a test. I like cheese." = "Đây là bài kiểm tra. Tôi thích phô mai."
  }
}

function Localize-Text($stem, $id, $english) {
  $map = $common[$stem]
  if ($map.ContainsKey($english)) { return $map[$english] }
  if ($id -like "ui_mercenary_custom_*") { return $english }
  if ($id -like "a614a_story*") { return $english }
  if ($id -like "merc_provider_*") {
    switch ($stem) {
      "Polish_xml" { return "Już się tym zajmę." }
      "Portuguese_xml" { return "Vou tratar disso." }
      "Spanish_xml" { return "Me ocuparé de ello." }
      "Ukrainian_xml" { return "Я цим займуся." }
      "Vietnamese_xml" { return "Tôi sẽ lo việc đó." }
    }
  }
  return $english
}

foreach ($stem in $common.Keys) {
  $builder = [System.Text.StringBuilder]::new()
  [void]$builder.AppendLine("<Table>")
  foreach ($row in $source.Table.Row) {
    $id = $row.Cell[0]."#text"
    $english = $row.Cell[1]."#text"
    $localized = Localize-Text $stem $id $english
    $id = [System.Security.SecurityElement]::Escape($id)
    $english = [System.Security.SecurityElement]::Escape($english)
    $localized = [System.Security.SecurityElement]::Escape($localized)
    [void]$builder.AppendLine("  <Row><Cell>$id</Cell><Cell>$english</Cell><Cell>$localized</Cell></Row>")
  }
  [void]$builder.AppendLine("</Table>")
  [System.IO.File]::WriteAllText((Join-Path $locDir "$stem.xml"), $builder.ToString(), [System.Text.UTF8Encoding]::new($false))
}
