"""Regenerate the 12 merc_skalitz_* clothing presets from the authored spec below.

Style 6 is the one hand-authored wardrobe (every other style is generated by the
outfit budget tooling), and it is the only one with a LIVERY: a Skalitz waffenrock,
hood and mail collar. Those livery pieces are **not vanilla** - they come from the
third-party *House of Kobyla Arms, Armour and Regalia* mod, which is exactly why the
outfit label carries a "requires ..." note. Without that mod the base layers still
equip and the men simply turn out without the surcoat.

That is also the bug this file fixes: the shipped presets had lost every livery piece
and kept only the plain vanilla base, so a Skalitz merc was assembled from the same
pool as style 1 and looked generic - reported as "Skalitz armour reverts to generic
style". The spec here is the authored intent, restored.

    python tools/gen_skalitz_presets.py           # rewrite the presets in place
    python tools/gen_skalitz_presets.py --check   # verify only, change nothing

Editing the look = editing SPEC below, then re-running. Do not hand-edit the XML: the
four variants per tier are derived, and hand edits collapse them back into duplicates
(which is how the last regression happened - _1/_3 and _2/_4 went byte-identical).
"""

import argparse
import io
import itertools
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PRESETS = os.path.join(REPO, "data", "libs", "tables", "item",
                       "clothing_preset__mercenaries.xml")
VANILLA_GLOB = os.path.join(REPO, "references", "base_game", "Libs", "Tables", "item")

# Items that live in House of Kobyla Arms, Armour and Regalia, not in vanilla. Listed
# by GUID because there is no local table to resolve their names from.
KOBYLA = {
    "1a8b1d97-f280-43db-aa5a-68ed064647db": "Collar: Skalitz mail collar (Kobyla)",
    "61877793-794d-4f0f-8ccd-b3d7d03e9b80": "Waffenrock: Skalitz surcoat A (Kobyla)",
    "f964c4c9-2929-443f-bfcd-78dcdb55ee0b": "Waffenrock: Skalitz surcoat B (Kobyla)",
    "18aa14c1-acbf-453b-bfc5-2c55d29a96fd": "Hood: Plain red Skalitz hood (Kobyla)",
    "16798160-94ae-4cd3-8f7c-f06c96f9f44b": "Waffenrock: Skalitz surcoat C (Kobyla)",
    "5b3d2485-1c83-48f4-afc7-ae62f97b99a7": "Waffenrock: Skalitz surcoat D (Kobyla)",
}

# Slot order is the order items are written into each preset.
SLOTS = ["Boots", "Gloves", "Legs", "Leg armor", "Gambeson", "Chainmail", "Coif",
         "Chest", "Collar", "Sleeves", "Waffenrock", "Hood", "Helmet"]

# The authored spec. A string is a vanilla item resolved BY NAME from the comments
# already in the preset file; a list of two is an either/or that the four variants
# permute; None means the slot is deliberately empty for that tier.
SPEC = {
    "weak": {
        "Boots":      "BootsAnkle02_m01_B",
        "Gloves":     "Gloves05_m02_B2",
        "Legs":       "LegsPadded01_m09_C3",
        "Leg armor":  "LegsPlate07_m01_E1",
        "Gambeson":   "GambesonLong01_m04_C3",
        "Chainmail":  "MailShort01_m01_C4",
        "Coif":       "CoifSmall01_m04_C2",
        "Chest":      None,                       # tier 1 wears no chest by design
        "Collar":     ["CollarChain01_m04_C1", "1a8b1d97-f280-43db-aa5a-68ed064647db"],
        "Sleeves":    "ArmPlate01_m03_C2",
        "Waffenrock": ["61877793-794d-4f0f-8ccd-b3d7d03e9b80",
                       "f964c4c9-2929-443f-bfcd-78dcdb55ee0b"],
        "Hood":       "18aa14c1-acbf-453b-bfc5-2c55d29a96fd",
        "Helmet":     ["KettleHat04_m05_B4", "KettleHat01_m01_E1"],
    },
    "medium": {
        "Boots":      "BootsAnkle02_m01_B",
        "Gloves":     "Gloves05_m02_B2",
        "Legs":       "LegsPadded01_m08_C3",
        "Leg armor":  ["LegsBrigandine01_m08_D2", "LegsBrigandine04_m02_A5"],
        "Gambeson":   "GambesonLong01_m04_C3",
        "Chainmail":  "MailShort01_m01_C4",
        "Coif":       "CoifMail01_m04_C2",
        "Chest":      ["Cuirass05_m04_B3", "Brigandine03_m05_A4"],
        "Collar":     ["CollarChain01_m04_C1", "1a8b1d97-f280-43db-aa5a-68ed064647db"],
        "Sleeves":    "ArmPlate02_m01_C3",
        "Waffenrock": ["16798160-94ae-4cd3-8f7c-f06c96f9f44b",
                       "5b3d2485-1c83-48f4-afc7-ae62f97b99a7"],
        "Hood":       "18aa14c1-acbf-453b-bfc5-2c55d29a96fd",
        "Helmet":     ["BascinetOpen08_m01_B3", "KettleHat03_m01_B3"],
    },
    "strong": {
        "Boots":      "BootsAnkle02_m01_B",
        "Gloves":     "Gloves05_m02_B2",
        "Legs":       "LegsPadded01_m08_C3",
        "Leg armor":  ["LegsPlate05_m04_C3", "LegsPlate02_m03_B4"],
        "Gambeson":   "GambesonLong01_m04_C3",
        "Chainmail":  "MailShort01_m01_C4",
        "Coif":       "CoifMail01_m04_C2",
        # NOT in the authored list, which jumps from Coif straight to Collar. Kept
        # because the strong tier having no chestplate was a REPORTED BUG, fixed by
        # adding this same primary/alt split (TODO.txt, "fixed the strong-tier Skalitz
        # outfits having no chestplate"). Set to None to go chestless again.
        "Chest":      ["Cuirass05_m04_B3", "Brigandine03_m05_A4"],
        "Collar":     ["CollarChain01_m04_C1", "1a8b1d97-f280-43db-aa5a-68ed064647db"],
        "Sleeves":    "ArmPlate02_m01_C3",
        "Waffenrock": ["16798160-94ae-4cd3-8f7c-f06c96f9f44b",
                       "5b3d2485-1c83-48f4-afc7-ae62f97b99a7"],
        "Hood":       None,                       # tier 3 goes bare-headed under the helm
        "Helmet":     ["BascinetVisor02_m03_D3", "BascinetVisor01_m05_C3"],
    },
}

BLOCK = re.compile(
    r'(<clothing_preset [^>]*clothing_preset_name="(merc_skalitz_(\w+?)_(\d))"[^>]*>)'
    r'(.*?)'
    r'(</clothing_preset>)', re.S)

GUID_RE = re.compile(r'^[0-9a-fA-F-]{36}$')


def name_map(text):
    """name -> guid, harvested from the item comments already in the preset file."""
    out = {}
    for guid, comment in re.findall(r'<Guid>([0-9a-fA-F-]{36})</Guid>\s*<!--\s*(.*?)-->', text):
        c = comment.strip()
        if ":" in c:
            nm = re.sub(r'\s*\(alt\)\s*$', '', c.split(":", 1)[1].strip())
            out.setdefault(nm, guid)
    return out


def vanilla_ids():
    blob = []
    if os.path.isdir(VANILLA_GLOB):
        for fn in os.listdir(VANILLA_GLOB):
            if fn.startswith("item") and fn.endswith(".xml"):
                blob.append(io.open(os.path.join(VANILLA_GLOB, fn),
                                    encoding="utf-8", errors="replace").read())
    return set(re.findall(r'Id="([0-9a-fA-F-]{36})"', "\n".join(blob)))


def pick_codewords(n_slots):
    """Four assignments over n binary slots, chosen for the largest minimum pairwise
    difference, so no two variants of a tier differ in only one piece - which is what
    made them read as 'the same outfit' before."""
    best, best_score = None, -1
    for combo in itertools.combinations(itertools.product((0, 1), repeat=n_slots), 4):
        if combo[0] != tuple([0] * n_slots):
            continue                      # variant _1 is always the all-primary look
        score = min(sum(a != b for a, b in zip(x, y))
                    for x, y in itertools.combinations(combo, 2))
        if score > best_score:
            best, best_score = combo, score
    return best, best_score


def build():
    text = io.open(PRESETS, encoding="utf-8-sig", newline="").read()
    names = name_map(text)
    van = vanilla_ids()

    problems = []
    resolved = {}          # (tier, slot, option index) -> (guid, label)
    for tier, slots in SPEC.items():
        for slot, val in slots.items():
            if val is None:
                continue
            opts = val if isinstance(val, list) else [val]
            for i, o in enumerate(opts):
                if GUID_RE.match(o):
                    guid, label = o, KOBYLA.get(o, slot + ": (unnamed)")
                else:
                    guid = names.get(o)
                    label = "%s: %s" % (slot, o)
                    if not guid:
                        problems.append("%s/%s: cannot resolve name %r" % (tier, slot, o))
                        continue
                if guid not in van and guid not in KOBYLA:
                    problems.append("%s/%s: %s is neither vanilla nor a known Kobyla item"
                                    % (tier, slot, guid))
                resolved[(tier, slot, i)] = (guid, label)
    if problems:
        for p in problems:
            print("ERROR " + p)
        raise SystemExit("spec did not validate - nothing written")

    written = []
    for tier in ("weak", "medium", "strong"):
        slots = SPEC[tier]
        variable = [s for s in SLOTS if isinstance(slots.get(s), list)]
        codes, spread = pick_codewords(len(variable))
        print("%-7s %d either/or slot(s) %s -> min variant difference %d piece(s)"
              % (tier, len(variable), variable, spread))
        for v in range(4):
            code = codes[v]
            lines = []
            for slot in SLOTS:
                val = slots.get(slot)
                if val is None:
                    continue
                idx = code[variable.index(slot)] if slot in variable else 0
                guid, label = resolved[(tier, slot, idx)]
                lines.append("                <Guid>%s</Guid> <!-- %s -->" % (guid, label))
            name = "merc_skalitz_%s_%d" % (tier, v + 1)
            body = ("\n            <Items>\n" + "\n".join(lines)
                    + "\n            </Items>\n        ")

            def repl(m, _n=name, _b=body):
                return m.group(1) + _b + m.group(6) if m.group(2) == _n else m.group(0)

            new = BLOCK.sub(repl, text)
            if new == text:
                raise SystemExit("no preset named " + name)
            text, _ = new, written.append((name, len(lines)))

    io.open(PRESETS, "w", encoding="utf-8-sig", newline="").write(text)
    for n, c in written:
        print("  wrote %-24s %2d items" % (n, c))
    return text


def check(text=None):
    text = text if text is not None else io.open(PRESETS, encoding="utf-8-sig").read()
    blocks = re.findall(
        r'<clothing_preset [^>]*clothing_preset_name="(merc_skalitz[^"]+)"[^>]*>(.*?)</clothing_preset>',
        text, re.S)
    sets = {n: [g for g in re.findall(r'<Guid>([0-9a-fA-F-]{36})</Guid>', b)] for n, b in blocks}
    ok = True
    if len(sets) != 12:
        print("FAIL expected 12 presets, found %d" % len(sets)); ok = False
    dups = [(a, b) for a, b in itertools.combinations(sorted(sets), 2) if sets[a] == sets[b]]
    if dups:
        print("FAIL duplicate presets: %s" % dups); ok = False
    for n, guids in sets.items():
        if len(guids) != len(set(guids)):
            print("FAIL %s repeats an item" % n); ok = False
    van = vanilla_ids()
    used = {g for v in sets.values() for g in v}
    unknown = [g for g in used if g not in van and g not in KOBYLA]
    if unknown:
        print("FAIL items neither vanilla nor known-Kobyla: %s" % unknown); ok = False
    print("check: 12 presets, all distinct, %d Kobyla livery item(s) in use, %s"
          % (len({g for g in used if g in KOBYLA}), "OK" if ok else "PROBLEMS"))
    return ok


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="verify only, write nothing")
    a = ap.parse_args()
    sys.exit(0 if (check() if a.check else check(build())) else 1)
