"""Generate data/Scripts/mods/mercenaries_price_data.lua - item class GUID -> base price.

The camp trader has to put a number on whatever the player drops on his counter, and that
can be ANY of the game's 5,000-odd item classes. The scriptbind offers no price getter that
is known to work from Lua (`ItemManager.GetItem` hands back an item whose `CurrentUnitPrice`
field may or may not be readable - mercenaries_trader.lua tries it first and falls back to
this table), so the authoritative figure is read out of the game's own item tables offline,
exactly as tools/gen_gear_table.py does for equipment slots.

Source: references/Libs/Tables/item/item*.xml, `Price` attribute on every row that has an
`Id` and a `Name`. Prices are the BASE price of a pristine unit; the trader scales by the
item's health and by his own buy/sell margins.

    python tools/gen_price_table.py

Never hand-edit the generated Lua.
"""

import glob
import io
import os
import re

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(REPO, "references", "Libs", "Tables", "item")
DST = os.path.join(REPO, "data", "Scripts", "mods", "mercenaries_price_data.lua")

# One record is 32 hex digits of dashless GUID + 6 decimal digits of price, no separator.
# Fixed width so the Lua side can walk the blob with string.sub and no pattern matching.
GUID_W = 32
PRICE_W = 6
PRICE_MAX = 10 ** PRICE_W - 1

ROW = re.compile(r"<(\w+)\b([^>]*?)/?>")
ATTR = re.compile(r'\b(\w+)="([^"]*)"')

# Chunked so no single Lua string literal gets silly; the loader concatenates them.
CHUNK = 64


def read_prices():
    out = {}
    for path in sorted(glob.glob(os.path.join(SRC, "item*.xml"))):
        with io.open(path, "r", encoding="us-ascii", errors="replace") as fh:
            text = fh.read()
        for m in ROW.finditer(text):
            attrs = dict(ATTR.findall(m.group(2)))
            guid = attrs.get("Id")
            if not guid or "Name" not in attrs or "Price" not in attrs:
                continue
            try:
                price = int(round(float(attrs["Price"])))
            except ValueError:
                continue
            if price <= 0:
                continue
            key = guid.replace("-", "").lower()
            if len(key) != GUID_W:
                continue
            # A later table overriding an earlier one is the game's own behaviour.
            out[key] = min(price, PRICE_MAX)
    return out


def main():
    prices = read_prices()
    keys = sorted(prices)
    records = ["%s%0*d" % (k, PRICE_W, prices[k]) for k in keys]

    lines = [
        "-- GENERATED by tools/gen_price_table.py - do not edit by hand.",
        "-- Source: references/Libs/Tables/item/item*.xml (the `Price` attribute).",
        "--",
        "-- Item class GUID -> base price in groschen, for the camp trader's counter. Packed",
        "-- as fixed-width records (32 hex digits of dashless GUID + 6 digits of price) and",
        "-- unpacked lazily on the first trade - see mercenaries_trader.lua TraderBasePrice.",
        "",
        "mercenaries.PriceBlobs = {",
    ]
    for i in range(0, len(records), CHUNK):
        lines.append('    "' + "".join(records[i:i + CHUNK]) + '",')
    lines.append("}")
    lines.append("")
    lines.append("mercenaries.PriceCount = %d" % len(records))
    lines.append("")

    with io.open(DST, "w", encoding="ascii", newline="\n") as fh:
        fh.write("\n".join(lines))
    print("mercenaries_price_data.lua  %d item classes, %.1f KB"
          % (len(records), os.path.getsize(DST) / 1024.0))


if __name__ == "__main__":
    main()
