# Generates data/Scripts/mods/mercenaries_gear_data.lua - the GUID -> equipment-slot
# (armour) and GUID -> weapon-class (weapons) lookup the custom gear set needs.
#
# There is no runtime bind that reports an item's slot or category, so it has to be
# baked. Source is the extracted vanilla tables under references/Libs/Tables/item/.
# Re-run after a game patch:  python tools/gen_gear_table.py
import os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TBL  = os.path.join(ROOT, "references", "Libs", "Tables", "item")
OUT  = os.path.join(ROOT, "data", "Scripts", "mods", "mercenaries_gear_data.lua")

def read(name):
    with open(os.path.join(TBL, name), encoding="ascii", errors="ignore") as f:
        return f.read()

def attrs(tag):
    return dict(re.findall(r'(\w+)="([^"]*)"', tag))

# ---- armor_type name -> equipment slot id -------------------------------------
# equipment_slot.xml lists ArmorTypes for the slots that have layering rules; the
# rest (coats, gloves, boots, collars, hoods, jewellery, horse tack) carry no
# ArmorTypes attribute at all, so those are mapped by hand from the slot names.
slot_of_type = {}
slot_name = {}
for tag in re.findall(r'<EquipmentSlot[^>]*/>', read("equipment_slot.xml")):
    a = attrs(tag)
    sid = int(a["Id"])
    slot_name[sid] = a.get("Name", "")
    for t in (a.get("ArmorTypes") or "").split():
        slot_of_type[t] = sid

MANUAL = {
    "Coat": 7, "Waffenrock": 7, "Habit": 7,
    "Gauntlets": 8, "Gloves": 8,
    "CollarPadded": 22, "CollarMail": 22,
    "Hood": 23,
    "Shoes": 30, "BootsAnkle": 30, "BootsKnee": 30, "F_Shoes": 30,
    "Ring": 18, "Necklace": 19,
    "Belt": 44, "Pouch": 45,
    # Horse tack - deliberately mapped so it can be RECOGNISED and then rejected.
    "Bridle": 14, "Saddle": 16, "Caparison": 13, "HorsePlate": 13,
    "HorsePadded": 13, "HorseShoe": 21,
}
for k, v in MANUAL.items():
    slot_of_type.setdefault(k, v)

armor_types = [attrs(t)["Name"] for t in re.findall(r'<armor_type[^>]*/>', read("armor_type.xml"))]
# Clothing names not covered by the (week-older) armor_type table. Longest-prefix
# match still needs something to hit, so these map straight to a slot.
EXTRA_PREFIX = {
    "BascinetAlberich": 34, "BascinetHans": 34, "BascinetVisorHans": 34,
    "HoodAlbik": 23, "HandWrap": 8,
    "F_Cotehardie": 7, "F_Surcote": 7, "F_Kirtle": 35, "F_Chemise": 35,
    "F_Wreath": 33, "F_HairDecor": 33, "F_Hairnet": 33, "F_Crown": 33,
    "F_Cap": 33, "Wreath": 33, "CollarChain": 22, "WarChanfron": 14,
}
prefixes = sorted(
    [(n, slot_of_type[n]) for n in armor_types if n in slot_of_type] + list(EXTRA_PREFIX.items()),
    key=lambda p: -len(p[0]))

def slot_for(a):
    base = a.get("Clothing") or a.get("Name") or ""
    for name, sid in prefixes:
        if base.startswith(name):
            return sid
    return 0

# ---- parse item.xml -----------------------------------------------------------
items = re.findall(r'<(Armor|Helmet|Hood|MeleeWeapon|MissileWeapon|ItemAlias)\b([^>]*)/>', read("item.xml"))

by_slot, by_wclass, quest, aliases = {}, {}, [], []
for tag, body in items:
    a = attrs("<x " + body + ">")
    gid = a.get("Id")
    if not gid:
        continue
    isq = a.get("IsQuestItem") == "true"
    if tag == "ItemAlias":
        aliases.append((gid, a.get("SourceItemId"), isq))
        continue
    if tag in ("Armor", "Helmet", "Hood"):
        by_slot.setdefault(slot_for(a), []).append(gid)
    else:
        by_wclass.setdefault(int(a.get("Class", "-1")), []).append(gid)
    if isq:
        quest.append(gid)

# An alias is a relabelled copy of a real item - grade it as its source.
src_slot  = {g: s for s, gs in by_slot.items() for g in gs}
src_wcls  = {g: c for c, gs in by_wclass.items() for g in gs}
for gid, src, isq in aliases:
    if src in src_slot:
        by_slot.setdefault(src_slot[src], []).append(gid)
    elif src in src_wcls:
        by_wclass.setdefault(src_wcls[src], []).append(gid)
    else:
        continue
    if isq:
        quest.append(gid)

# ---- emit ---------------------------------------------------------------------
def blobs(guids, per=64):
    flat = "".join(g.replace("-", "") for g in sorted(set(guids)))
    return [flat[i:i + per * 32] for i in range(0, len(flat), per * 32)]

def emit(f, table, comment_of):
    for key in sorted(table):
        chunks = blobs(table[key])
        f.write("    [%d] = {   -- %s (%d)\n" % (key, comment_of(key), len(set(table[key]))))
        for c in chunks:
            f.write('        "%s",\n' % c)
        f.write("    },\n")

wclass_name = {}
for tag in re.findall(r'<(?:MeleeWeaponClass|MissileWeaponClass)[^>]*/>', read("weapon_class.xml")):
    a = attrs(tag)
    wclass_name[int(a["id"])] = a["name"]

with open(OUT, "w", encoding="utf-8", newline="\n") as f:
    f.write("-- GENERATED by tools/gen_gear_table.py - do not edit by hand.\n")
    f.write("-- GUID -> equipment slot / weapon class for every vanilla armour piece and\n")
    f.write("-- weapon. Nothing in the scriptbind reports either, and the custom gear set\n")
    f.write("-- needs both (layer order, the gambeson rule, weapon vs armour). GUIDs are\n")
    f.write("-- stored dashless and concatenated 32 chars apiece; mercenaries_custom_gear.lua\n")
    f.write("-- unpacks them lazily on first use. See docs/custom-gear.md.\n\n")
    f.write("mercenaries.GearSlotBlobs = {\n")
    emit(f, by_slot, lambda k: slot_name.get(k, "unknown"))
    f.write("}\n\nmercenaries.GearWeaponBlobs = {\n")
    emit(f, by_wclass, lambda k: wclass_name.get(k, "unknown"))
    f.write("}\n\n")
    f.write("-- IsQuestItem blocks inventory:CreateItem outright, so a quest piece can never\n")
    f.write("-- be copied onto a merc - it is refused at the wardrobe instead of failing mute.\n")
    f.write("mercenaries.GearQuestBlobs = {\n")
    for c in blobs(quest):
        f.write('    "%s",\n' % c)
    f.write("}\n")

n_arm = sum(len(set(v)) for v in by_slot.values())
n_wpn = sum(len(set(v)) for v in by_wclass.values())
print("armour %d (unknown slot: %d), weapons %d, quest %d -> %s"
      % (n_arm, len(set(by_slot.get(0, []))), n_wpn, len(set(quest)), os.path.relpath(OUT, ROOT)))
for s in sorted(by_slot):
    print("   slot %-3d %-20s %d" % (s, slot_name.get(s, "?"), len(set(by_slot[s]))))
for c in sorted(by_wclass):
    print("   wclass %-3d %-20s %d" % (c, wclass_name.get(c, "?"), len(set(by_wclass[c]))))
