"""Measure every mesh the camp spawns, straight out of the paks.

The camp validated every tent against one hardcoded box - `CampTentFootHalf`, 1.0 x 2.25 -
on the stated grounds that "every CampTentVariants entry shares the same footprint". They do
not. Measured, the five variants span 1.19 to 1.53 half-width and 1.46 to 2.33 half-length,
so `tent_small_rustic_a` is 60% longer than the box that approved its spot, and three of the
five are not even centred on their own origin (`tent_small_forest_d` sits 0.69 m off along
Y). That is the "tents sometimes have a larger blueprint" report.

This writes `data/Scripts/mods/mercenaries_camp_footprints.lua`, a generated table of what
each mesh actually measures, in MESH space:

    x, y   half-extents along the mesh's own X and Y
    ox, oy where the box centre sits relative to the origin the game spawns it at
    tall   height above that origin

Turning those into the placement frame is `CampPropFootHalf`'s job in
mercenaries_camp.lua - the meshes are spawned with a 90 degree facing fix, so the
placement frame's width is the mesh's Y and its depth is the mesh's X.

Usage
    python tools/measure_camp_props.py            # rewrite the generated table
    python tools/measure_camp_props.py --print    # just show the measurements

See docs/ground-guard.md and docs/camp.md.
"""
import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools"))
import cgf_mesh

PAKS = (r"C:/Program Files/Steam/steamapps/common/KingdomComeDeliverance2/Data/"
        r"*Objects-part*.pak")
CAMP_LUA = ROOT / "data/Scripts/mods/mercenaries_camp.lua"
OUT_LUA = ROOT / "data/Scripts/mods/mercenaries_camp_footprints.lua"

# Every table in mercenaries_camp.lua that names a mesh the camp puts on the ground.
TABLES = ("CampModels", "CampTentVariants", "CampTentClutterVariants",
          "CampTrainingDummyModels")
SCALARS = ("CampPlayerTentModel", "CampFireOverlayModel", "CampNightLightModel")


def models():
    """Every .cgf path the camp spawner names, in source order, de-duplicated."""
    src = CAMP_LUA.read_text(encoding="utf-8-sig", errors="replace")
    found, seen = [], set()

    def add(path):
        p = path.lower()
        if p.endswith(".cgf") and p not in seen:
            seen.add(p)
            found.append(p)

    for name in TABLES:
        m = re.search(r"mercenaries\.%s\s*=\s*\{" % name, src)
        if not m:
            print("  (no table %s - renamed?)" % name, file=sys.stderr)
            continue
        depth, i = 0, m.end() - 1
        while i < len(src):
            if src[i] == "{":
                depth += 1
            elif src[i] == "}":
                depth -= 1
                if depth == 0:
                    break
            i += 1
        for path in re.findall(r'"([^"]+\.cgf)"', src[m.end():i]):
            add(path)

    for name in SCALARS:
        m = re.search(r'mercenaries\.%s\s*=\s*"([^"]+)"' % name, src)
        if m:
            add(m.group(1))
    return found


def measure(pak, path):
    bb = cgf_mesh.bbox_of(pak, path)
    if bb is None:
        return None
    lo, hi = bb
    return dict(x=(hi[0] - lo[0]) / 2.0, y=(hi[1] - lo[1]) / 2.0,
                ox=(hi[0] + lo[0]) / 2.0, oy=(hi[1] + lo[1]) / 2.0,
                tall=float(hi[2]))


HEADER = '''-- GENERATED by tools/measure_camp_props.py - do not edit by hand.
--
-- What every mesh the camp spawns actually measures, read out of the object paks. The camp
-- used to validate every tent against one hardcoded box on the stated grounds that the
-- variants "share the same footprint"; they do not, and the spread below is why tents came
-- out overlapping what the map had approved.
--
-- MESH SPACE, metres:
--   x, y    half-extents along the mesh's own X and Y axes
--   ox, oy  where that box's centre sits relative to the origin it is spawned at - three of
--           the tents are not centred on their own origin at all
--   tall    height above that origin
--
-- CampPropFootHalf in mercenaries_camp.lua turns these into the placement frame. Re-run the
-- tool after adding a model to CampModels, CampTentVariants, CampTentClutterVariants,
-- CampTrainingDummyModels, CampPlayerTentModel, CampFireOverlayModel or CampNightLightModel.

mercenaries.CampPropFoot = {
'''


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--print", dest="show", action="store_true",
                    help="print the measurements instead of writing the table")
    a = ap.parse_args()

    pak = cgf_mesh.Pak(PAKS)
    rows, missing = [], []
    for path in models():
        m = measure(pak, path)
        if m is None:
            missing.append(path)
            continue
        rows.append((path, m))

    width = max((len(p) for p, _ in rows), default=0)
    if a.show:
        print("%-*s %6s %6s %7s %7s %6s" % (width, "model", "x", "y", "ox", "oy", "tall"))
        for path, m in rows:
            print("%-*s %6.2f %6.2f %7.2f %7.2f %6.2f"
                  % (width, path, m["x"], m["y"], m["ox"], m["oy"], m["tall"]))
    else:
        out = [HEADER]
        for path, m in rows:
            out.append('    ["%s"] =%s{ x = %.2f, y = %.2f, ox = %.2f, oy = %.2f, tall = %.2f },\n'
                       % (path, " " * (width - len(path) + 1),
                          m["x"], m["y"], m["ox"], m["oy"], m["tall"]))
        out.append("}\n")
        OUT_LUA.write_text("".join(out), encoding="utf-8", newline="\n")
        print("wrote %s (%d mesh(es))" % (OUT_LUA.relative_to(ROOT), len(rows)))

    for path in missing:
        print("  NOT IN THE PAKS: %s" % path, file=sys.stderr)
    return 1 if missing else 0


if __name__ == "__main__":
    sys.exit(main())
